// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.client.proto;

public interface FileStreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.Comms.ClientProto.FileStreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The unique identifier for the job that created the file
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The job.
   */
  java.lang.String getJob();
  /**
   * <pre>
   *The unique identifier for the job that created the file
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The bytes for job.
   */
  com.google.protobuf.ByteString
      getJobBytes();

  /**
   * <pre>
   *The name of the file including any relative paths within the job directory
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <pre>
   *The name of the file including any relative paths within the job directory
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   *The offset into the file (in bytes) to start returning from
   * </pre>
   *
   * <code>int64 offset = 3;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <pre>
   *RPC server address to use for transferring the file if available
   * </pre>
   *
   * <code>.google.protobuf.StringValue rpc_address = 4;</code>
   * @return Whether the rpcAddress field is set.
   */
  boolean hasRpcAddress();
  /**
   * <pre>
   *RPC server address to use for transferring the file if available
   * </pre>
   *
   * <code>.google.protobuf.StringValue rpc_address = 4;</code>
   * @return The rpcAddress.
   */
  com.google.protobuf.StringValue getRpcAddress();
  /**
   * <pre>
   *RPC server address to use for transferring the file if available
   * </pre>
   *
   * <code>.google.protobuf.StringValue rpc_address = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getRpcAddressOrBuilder();

  /**
   * <pre>
   *RPC server address to use for transferring a file within the local network
   * </pre>
   *
   * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
   * @return Whether the internalRpcAddress field is set.
   */
  boolean hasInternalRpcAddress();
  /**
   * <pre>
   *RPC server address to use for transferring a file within the local network
   * </pre>
   *
   * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
   * @return The internalRpcAddress.
   */
  com.google.protobuf.StringValue getInternalRpcAddress();
  /**
   * <pre>
   *RPC server address to use for transferring a file within the local network
   * </pre>
   *
   * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
   */
  com.google.protobuf.StringValueOrBuilder getInternalRpcAddressOrBuilder();

  /**
   * <pre>
   *Compress the stream transferred over MQTT
   * </pre>
   *
   * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
   * @return Whether the compressStream field is set.
   */
  boolean hasCompressStream();
  /**
   * <pre>
   *Compress the stream transferred over MQTT
   * </pre>
   *
   * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
   * @return The compressStream.
   */
  com.google.protobuf.BoolValue getCompressStream();
  /**
   * <pre>
   *Compress the stream transferred over MQTT
   * </pre>
   *
   * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getCompressStreamOrBuilder();
}
