// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.client.proto;

public final class FileUpload {
  private FileUpload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ClientProto_FileStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ClientProto_FileStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ClientProto_FileStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ClientProto_FileStreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ClientProto_FileStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ClientProto_FileStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021file_upload.proto\022\026WISE.Comms.ClientPr" +
      "oto\032\036google/protobuf/wrappers.proto\"Z\n\021F" +
      "ileStreamRequest\022\013\n\003job\030\001 \001(\t\022\020\n\010filenam" +
      "e\030\002 \001(\t\022\021\n\tfile_size\030\003 \001(\003\022\023\n\013was_skippe" +
      "d\030\004 \001(\010\"\347\001\n\022FileStreamResponse\022\013\n\003job\030\001 " +
      "\001(\t\022\020\n\010filename\030\002 \001(\t\022\016\n\006offset\030\003 \001(\003\0221\n" +
      "\013rpc_address\030\004 \001(\0132\034.google.protobuf.Str" +
      "ingValue\022:\n\024internal_rpc_address\030\005 \001(\0132\034" +
      ".google.protobuf.StringValue\0223\n\017compress" +
      "_stream\030\006 \001(\0132\032.google.protobuf.BoolValu" +
      "e\"\231\001\n\nFileStream\022\013\n\003job\030\001 \001(\t\022\020\n\010filenam" +
      "e\030\002 \001(\t\022\026\n\016is_end_of_file\030\003 \001(\010\022\021\n\tfile_" +
      "size\030\004 \001(\003\022\014\n\004data\030\005 \001(\014\0223\n\017compress_str" +
      "eam\030\006 \001(\0132\032.google.protobuf.BoolValueB7\n" +
      "\032ca.wise.comms.client.protoP\001\252\002\026WISE.Com" +
      "ms.ClientProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_WISE_Comms_ClientProto_FileStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_Comms_ClientProto_FileStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ClientProto_FileStreamRequest_descriptor,
        new java.lang.String[] { "Job", "Filename", "FileSize", "WasSkipped", });
    internal_static_WISE_Comms_ClientProto_FileStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WISE_Comms_ClientProto_FileStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ClientProto_FileStreamResponse_descriptor,
        new java.lang.String[] { "Job", "Filename", "Offset", "RpcAddress", "InternalRpcAddress", "CompressStream", });
    internal_static_WISE_Comms_ClientProto_FileStream_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WISE_Comms_ClientProto_FileStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ClientProto_FileStream_descriptor,
        new java.lang.String[] { "Job", "Filename", "IsEndOfFile", "FileSize", "Data", "CompressStream", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
