// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.client.proto;

public interface FileStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.Comms.ClientProto.FileStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The unique identifier for the job that created the file
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The job.
   */
  java.lang.String getJob();
  /**
   * <pre>
   *The unique identifier for the job that created the file
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The bytes for job.
   */
  com.google.protobuf.ByteString
      getJobBytes();

  /**
   * <pre>
   *The name of the file including any relative paths within the job directory
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <pre>
   *The name of the file including any relative paths within the job directory
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   *Has the end of the file been reached
   * </pre>
   *
   * <code>bool is_end_of_file = 3;</code>
   * @return The isEndOfFile.
   */
  boolean getIsEndOfFile();

  /**
   * <pre>
   *The size of the file in bytes
   * </pre>
   *
   * <code>int64 file_size = 4;</code>
   * @return The fileSize.
   */
  long getFileSize();

  /**
   * <pre>
   *A set of bytes from the file starting at the requested offset
   * </pre>
   *
   * <code>bytes data = 5;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   *Has the stream been compressed
   * </pre>
   *
   * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
   * @return Whether the compressStream field is set.
   */
  boolean hasCompressStream();
  /**
   * <pre>
   *Has the stream been compressed
   * </pre>
   *
   * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
   * @return The compressStream.
   */
  com.google.protobuf.BoolValue getCompressStream();
  /**
   * <pre>
   *Has the stream been compressed
   * </pre>
   *
   * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getCompressStreamOrBuilder();
}
