// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.client.proto;

/**
 * <pre>
 **
 * A response to W.I.S.E. Manager that you are
 * looking to receive the file over MQTT.
 * </pre>
 *
 * Protobuf type {@code WISE.Comms.ClientProto.FileStreamResponse}
 */
public final class FileStreamResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.Comms.ClientProto.FileStreamResponse)
    FileStreamResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileStreamResponse.newBuilder() to construct.
  private FileStreamResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileStreamResponse() {
    job_ = "";
    filename_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileStreamResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileStreamResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            job_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            filename_ = s;
            break;
          }
          case 24: {

            offset_ = input.readInt64();
            break;
          }
          case 34: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (rpcAddress_ != null) {
              subBuilder = rpcAddress_.toBuilder();
            }
            rpcAddress_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rpcAddress_);
              rpcAddress_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (internalRpcAddress_ != null) {
              subBuilder = internalRpcAddress_.toBuilder();
            }
            internalRpcAddress_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(internalRpcAddress_);
              internalRpcAddress_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (compressStream_ != null) {
              subBuilder = compressStream_.toBuilder();
            }
            compressStream_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(compressStream_);
              compressStream_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.comms.client.proto.FileUpload.internal_static_WISE_Comms_ClientProto_FileStreamResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.comms.client.proto.FileUpload.internal_static_WISE_Comms_ClientProto_FileStreamResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.comms.client.proto.FileStreamResponse.class, ca.wise.comms.client.proto.FileStreamResponse.Builder.class);
  }

  public static final int JOB_FIELD_NUMBER = 1;
  private volatile java.lang.Object job_;
  /**
   * <pre>
   *The unique identifier for the job that created the file
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The job.
   */
  @java.lang.Override
  public java.lang.String getJob() {
    java.lang.Object ref = job_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      job_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The unique identifier for the job that created the file
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The bytes for job.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobBytes() {
    java.lang.Object ref = job_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      job_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object filename_;
  /**
   * <pre>
   *The name of the file including any relative paths within the job directory
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  @java.lang.Override
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The name of the file including any relative paths within the job directory
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFSET_FIELD_NUMBER = 3;
  private long offset_;
  /**
   * <pre>
   *The offset into the file (in bytes) to start returning from
   * </pre>
   *
   * <code>int64 offset = 3;</code>
   * @return The offset.
   */
  @java.lang.Override
  public long getOffset() {
    return offset_;
  }

  public static final int RPC_ADDRESS_FIELD_NUMBER = 4;
  private com.google.protobuf.StringValue rpcAddress_;
  /**
   * <pre>
   *RPC server address to use for transferring the file if available
   * </pre>
   *
   * <code>.google.protobuf.StringValue rpc_address = 4;</code>
   * @return Whether the rpcAddress field is set.
   */
  @java.lang.Override
  public boolean hasRpcAddress() {
    return rpcAddress_ != null;
  }
  /**
   * <pre>
   *RPC server address to use for transferring the file if available
   * </pre>
   *
   * <code>.google.protobuf.StringValue rpc_address = 4;</code>
   * @return The rpcAddress.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getRpcAddress() {
    return rpcAddress_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : rpcAddress_;
  }
  /**
   * <pre>
   *RPC server address to use for transferring the file if available
   * </pre>
   *
   * <code>.google.protobuf.StringValue rpc_address = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getRpcAddressOrBuilder() {
    return getRpcAddress();
  }

  public static final int INTERNAL_RPC_ADDRESS_FIELD_NUMBER = 5;
  private com.google.protobuf.StringValue internalRpcAddress_;
  /**
   * <pre>
   *RPC server address to use for transferring a file within the local network
   * </pre>
   *
   * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
   * @return Whether the internalRpcAddress field is set.
   */
  @java.lang.Override
  public boolean hasInternalRpcAddress() {
    return internalRpcAddress_ != null;
  }
  /**
   * <pre>
   *RPC server address to use for transferring a file within the local network
   * </pre>
   *
   * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
   * @return The internalRpcAddress.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getInternalRpcAddress() {
    return internalRpcAddress_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : internalRpcAddress_;
  }
  /**
   * <pre>
   *RPC server address to use for transferring a file within the local network
   * </pre>
   *
   * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getInternalRpcAddressOrBuilder() {
    return getInternalRpcAddress();
  }

  public static final int COMPRESS_STREAM_FIELD_NUMBER = 6;
  private com.google.protobuf.BoolValue compressStream_;
  /**
   * <pre>
   *Compress the stream transferred over MQTT
   * </pre>
   *
   * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
   * @return Whether the compressStream field is set.
   */
  @java.lang.Override
  public boolean hasCompressStream() {
    return compressStream_ != null;
  }
  /**
   * <pre>
   *Compress the stream transferred over MQTT
   * </pre>
   *
   * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
   * @return The compressStream.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getCompressStream() {
    return compressStream_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : compressStream_;
  }
  /**
   * <pre>
   *Compress the stream transferred over MQTT
   * </pre>
   *
   * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getCompressStreamOrBuilder() {
    return getCompressStream();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getJobBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, job_);
    }
    if (!getFilenameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filename_);
    }
    if (offset_ != 0L) {
      output.writeInt64(3, offset_);
    }
    if (rpcAddress_ != null) {
      output.writeMessage(4, getRpcAddress());
    }
    if (internalRpcAddress_ != null) {
      output.writeMessage(5, getInternalRpcAddress());
    }
    if (compressStream_ != null) {
      output.writeMessage(6, getCompressStream());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getJobBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, job_);
    }
    if (!getFilenameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filename_);
    }
    if (offset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, offset_);
    }
    if (rpcAddress_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRpcAddress());
    }
    if (internalRpcAddress_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getInternalRpcAddress());
    }
    if (compressStream_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCompressStream());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.comms.client.proto.FileStreamResponse)) {
      return super.equals(obj);
    }
    ca.wise.comms.client.proto.FileStreamResponse other = (ca.wise.comms.client.proto.FileStreamResponse) obj;

    if (!getJob()
        .equals(other.getJob())) return false;
    if (!getFilename()
        .equals(other.getFilename())) return false;
    if (getOffset()
        != other.getOffset()) return false;
    if (hasRpcAddress() != other.hasRpcAddress()) return false;
    if (hasRpcAddress()) {
      if (!getRpcAddress()
          .equals(other.getRpcAddress())) return false;
    }
    if (hasInternalRpcAddress() != other.hasInternalRpcAddress()) return false;
    if (hasInternalRpcAddress()) {
      if (!getInternalRpcAddress()
          .equals(other.getInternalRpcAddress())) return false;
    }
    if (hasCompressStream() != other.hasCompressStream()) return false;
    if (hasCompressStream()) {
      if (!getCompressStream()
          .equals(other.getCompressStream())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JOB_FIELD_NUMBER;
    hash = (53 * hash) + getJob().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOffset());
    if (hasRpcAddress()) {
      hash = (37 * hash) + RPC_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getRpcAddress().hashCode();
    }
    if (hasInternalRpcAddress()) {
      hash = (37 * hash) + INTERNAL_RPC_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getInternalRpcAddress().hashCode();
    }
    if (hasCompressStream()) {
      hash = (37 * hash) + COMPRESS_STREAM_FIELD_NUMBER;
      hash = (53 * hash) + getCompressStream().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.comms.client.proto.FileStreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.comms.client.proto.FileStreamResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * A response to W.I.S.E. Manager that you are
   * looking to receive the file over MQTT.
   * </pre>
   *
   * Protobuf type {@code WISE.Comms.ClientProto.FileStreamResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.Comms.ClientProto.FileStreamResponse)
      ca.wise.comms.client.proto.FileStreamResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.comms.client.proto.FileUpload.internal_static_WISE_Comms_ClientProto_FileStreamResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.comms.client.proto.FileUpload.internal_static_WISE_Comms_ClientProto_FileStreamResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.comms.client.proto.FileStreamResponse.class, ca.wise.comms.client.proto.FileStreamResponse.Builder.class);
    }

    // Construct using ca.wise.comms.client.proto.FileStreamResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      job_ = "";

      filename_ = "";

      offset_ = 0L;

      if (rpcAddressBuilder_ == null) {
        rpcAddress_ = null;
      } else {
        rpcAddress_ = null;
        rpcAddressBuilder_ = null;
      }
      if (internalRpcAddressBuilder_ == null) {
        internalRpcAddress_ = null;
      } else {
        internalRpcAddress_ = null;
        internalRpcAddressBuilder_ = null;
      }
      if (compressStreamBuilder_ == null) {
        compressStream_ = null;
      } else {
        compressStream_ = null;
        compressStreamBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.comms.client.proto.FileUpload.internal_static_WISE_Comms_ClientProto_FileStreamResponse_descriptor;
    }

    @java.lang.Override
    public ca.wise.comms.client.proto.FileStreamResponse getDefaultInstanceForType() {
      return ca.wise.comms.client.proto.FileStreamResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.comms.client.proto.FileStreamResponse build() {
      ca.wise.comms.client.proto.FileStreamResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.comms.client.proto.FileStreamResponse buildPartial() {
      ca.wise.comms.client.proto.FileStreamResponse result = new ca.wise.comms.client.proto.FileStreamResponse(this);
      result.job_ = job_;
      result.filename_ = filename_;
      result.offset_ = offset_;
      if (rpcAddressBuilder_ == null) {
        result.rpcAddress_ = rpcAddress_;
      } else {
        result.rpcAddress_ = rpcAddressBuilder_.build();
      }
      if (internalRpcAddressBuilder_ == null) {
        result.internalRpcAddress_ = internalRpcAddress_;
      } else {
        result.internalRpcAddress_ = internalRpcAddressBuilder_.build();
      }
      if (compressStreamBuilder_ == null) {
        result.compressStream_ = compressStream_;
      } else {
        result.compressStream_ = compressStreamBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.comms.client.proto.FileStreamResponse) {
        return mergeFrom((ca.wise.comms.client.proto.FileStreamResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.comms.client.proto.FileStreamResponse other) {
      if (other == ca.wise.comms.client.proto.FileStreamResponse.getDefaultInstance()) return this;
      if (!other.getJob().isEmpty()) {
        job_ = other.job_;
        onChanged();
      }
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        onChanged();
      }
      if (other.getOffset() != 0L) {
        setOffset(other.getOffset());
      }
      if (other.hasRpcAddress()) {
        mergeRpcAddress(other.getRpcAddress());
      }
      if (other.hasInternalRpcAddress()) {
        mergeInternalRpcAddress(other.getInternalRpcAddress());
      }
      if (other.hasCompressStream()) {
        mergeCompressStream(other.getCompressStream());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.comms.client.proto.FileStreamResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.comms.client.proto.FileStreamResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object job_ = "";
    /**
     * <pre>
     *The unique identifier for the job that created the file
     * </pre>
     *
     * <code>string job = 1;</code>
     * @return The job.
     */
    public java.lang.String getJob() {
      java.lang.Object ref = job_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        job_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The unique identifier for the job that created the file
     * </pre>
     *
     * <code>string job = 1;</code>
     * @return The bytes for job.
     */
    public com.google.protobuf.ByteString
        getJobBytes() {
      java.lang.Object ref = job_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        job_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The unique identifier for the job that created the file
     * </pre>
     *
     * <code>string job = 1;</code>
     * @param value The job to set.
     * @return This builder for chaining.
     */
    public Builder setJob(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      job_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The unique identifier for the job that created the file
     * </pre>
     *
     * <code>string job = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJob() {
      
      job_ = getDefaultInstance().getJob();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The unique identifier for the job that created the file
     * </pre>
     *
     * <code>string job = 1;</code>
     * @param value The bytes for job to set.
     * @return This builder for chaining.
     */
    public Builder setJobBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      job_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object filename_ = "";
    /**
     * <pre>
     *The name of the file including any relative paths within the job directory
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @return The filename.
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The name of the file including any relative paths within the job directory
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The name of the file including any relative paths within the job directory
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filename_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The name of the file including any relative paths within the job directory
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      
      filename_ = getDefaultInstance().getFilename();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The name of the file including any relative paths within the job directory
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filename_ = value;
      onChanged();
      return this;
    }

    private long offset_ ;
    /**
     * <pre>
     *The offset into the file (in bytes) to start returning from
     * </pre>
     *
     * <code>int64 offset = 3;</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }
    /**
     * <pre>
     *The offset into the file (in bytes) to start returning from
     * </pre>
     *
     * <code>int64 offset = 3;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(long value) {
      
      offset_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The offset into the file (in bytes) to start returning from
     * </pre>
     *
     * <code>int64 offset = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      
      offset_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.StringValue rpcAddress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> rpcAddressBuilder_;
    /**
     * <pre>
     *RPC server address to use for transferring the file if available
     * </pre>
     *
     * <code>.google.protobuf.StringValue rpc_address = 4;</code>
     * @return Whether the rpcAddress field is set.
     */
    public boolean hasRpcAddress() {
      return rpcAddressBuilder_ != null || rpcAddress_ != null;
    }
    /**
     * <pre>
     *RPC server address to use for transferring the file if available
     * </pre>
     *
     * <code>.google.protobuf.StringValue rpc_address = 4;</code>
     * @return The rpcAddress.
     */
    public com.google.protobuf.StringValue getRpcAddress() {
      if (rpcAddressBuilder_ == null) {
        return rpcAddress_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : rpcAddress_;
      } else {
        return rpcAddressBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *RPC server address to use for transferring the file if available
     * </pre>
     *
     * <code>.google.protobuf.StringValue rpc_address = 4;</code>
     */
    public Builder setRpcAddress(com.google.protobuf.StringValue value) {
      if (rpcAddressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rpcAddress_ = value;
        onChanged();
      } else {
        rpcAddressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *RPC server address to use for transferring the file if available
     * </pre>
     *
     * <code>.google.protobuf.StringValue rpc_address = 4;</code>
     */
    public Builder setRpcAddress(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (rpcAddressBuilder_ == null) {
        rpcAddress_ = builderForValue.build();
        onChanged();
      } else {
        rpcAddressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *RPC server address to use for transferring the file if available
     * </pre>
     *
     * <code>.google.protobuf.StringValue rpc_address = 4;</code>
     */
    public Builder mergeRpcAddress(com.google.protobuf.StringValue value) {
      if (rpcAddressBuilder_ == null) {
        if (rpcAddress_ != null) {
          rpcAddress_ =
            com.google.protobuf.StringValue.newBuilder(rpcAddress_).mergeFrom(value).buildPartial();
        } else {
          rpcAddress_ = value;
        }
        onChanged();
      } else {
        rpcAddressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *RPC server address to use for transferring the file if available
     * </pre>
     *
     * <code>.google.protobuf.StringValue rpc_address = 4;</code>
     */
    public Builder clearRpcAddress() {
      if (rpcAddressBuilder_ == null) {
        rpcAddress_ = null;
        onChanged();
      } else {
        rpcAddress_ = null;
        rpcAddressBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *RPC server address to use for transferring the file if available
     * </pre>
     *
     * <code>.google.protobuf.StringValue rpc_address = 4;</code>
     */
    public com.google.protobuf.StringValue.Builder getRpcAddressBuilder() {
      
      onChanged();
      return getRpcAddressFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *RPC server address to use for transferring the file if available
     * </pre>
     *
     * <code>.google.protobuf.StringValue rpc_address = 4;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getRpcAddressOrBuilder() {
      if (rpcAddressBuilder_ != null) {
        return rpcAddressBuilder_.getMessageOrBuilder();
      } else {
        return rpcAddress_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : rpcAddress_;
      }
    }
    /**
     * <pre>
     *RPC server address to use for transferring the file if available
     * </pre>
     *
     * <code>.google.protobuf.StringValue rpc_address = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getRpcAddressFieldBuilder() {
      if (rpcAddressBuilder_ == null) {
        rpcAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getRpcAddress(),
                getParentForChildren(),
                isClean());
        rpcAddress_ = null;
      }
      return rpcAddressBuilder_;
    }

    private com.google.protobuf.StringValue internalRpcAddress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> internalRpcAddressBuilder_;
    /**
     * <pre>
     *RPC server address to use for transferring a file within the local network
     * </pre>
     *
     * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
     * @return Whether the internalRpcAddress field is set.
     */
    public boolean hasInternalRpcAddress() {
      return internalRpcAddressBuilder_ != null || internalRpcAddress_ != null;
    }
    /**
     * <pre>
     *RPC server address to use for transferring a file within the local network
     * </pre>
     *
     * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
     * @return The internalRpcAddress.
     */
    public com.google.protobuf.StringValue getInternalRpcAddress() {
      if (internalRpcAddressBuilder_ == null) {
        return internalRpcAddress_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : internalRpcAddress_;
      } else {
        return internalRpcAddressBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *RPC server address to use for transferring a file within the local network
     * </pre>
     *
     * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
     */
    public Builder setInternalRpcAddress(com.google.protobuf.StringValue value) {
      if (internalRpcAddressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        internalRpcAddress_ = value;
        onChanged();
      } else {
        internalRpcAddressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *RPC server address to use for transferring a file within the local network
     * </pre>
     *
     * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
     */
    public Builder setInternalRpcAddress(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (internalRpcAddressBuilder_ == null) {
        internalRpcAddress_ = builderForValue.build();
        onChanged();
      } else {
        internalRpcAddressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *RPC server address to use for transferring a file within the local network
     * </pre>
     *
     * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
     */
    public Builder mergeInternalRpcAddress(com.google.protobuf.StringValue value) {
      if (internalRpcAddressBuilder_ == null) {
        if (internalRpcAddress_ != null) {
          internalRpcAddress_ =
            com.google.protobuf.StringValue.newBuilder(internalRpcAddress_).mergeFrom(value).buildPartial();
        } else {
          internalRpcAddress_ = value;
        }
        onChanged();
      } else {
        internalRpcAddressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *RPC server address to use for transferring a file within the local network
     * </pre>
     *
     * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
     */
    public Builder clearInternalRpcAddress() {
      if (internalRpcAddressBuilder_ == null) {
        internalRpcAddress_ = null;
        onChanged();
      } else {
        internalRpcAddress_ = null;
        internalRpcAddressBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *RPC server address to use for transferring a file within the local network
     * </pre>
     *
     * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
     */
    public com.google.protobuf.StringValue.Builder getInternalRpcAddressBuilder() {
      
      onChanged();
      return getInternalRpcAddressFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *RPC server address to use for transferring a file within the local network
     * </pre>
     *
     * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getInternalRpcAddressOrBuilder() {
      if (internalRpcAddressBuilder_ != null) {
        return internalRpcAddressBuilder_.getMessageOrBuilder();
      } else {
        return internalRpcAddress_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : internalRpcAddress_;
      }
    }
    /**
     * <pre>
     *RPC server address to use for transferring a file within the local network
     * </pre>
     *
     * <code>.google.protobuf.StringValue internal_rpc_address = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getInternalRpcAddressFieldBuilder() {
      if (internalRpcAddressBuilder_ == null) {
        internalRpcAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getInternalRpcAddress(),
                getParentForChildren(),
                isClean());
        internalRpcAddress_ = null;
      }
      return internalRpcAddressBuilder_;
    }

    private com.google.protobuf.BoolValue compressStream_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> compressStreamBuilder_;
    /**
     * <pre>
     *Compress the stream transferred over MQTT
     * </pre>
     *
     * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
     * @return Whether the compressStream field is set.
     */
    public boolean hasCompressStream() {
      return compressStreamBuilder_ != null || compressStream_ != null;
    }
    /**
     * <pre>
     *Compress the stream transferred over MQTT
     * </pre>
     *
     * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
     * @return The compressStream.
     */
    public com.google.protobuf.BoolValue getCompressStream() {
      if (compressStreamBuilder_ == null) {
        return compressStream_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : compressStream_;
      } else {
        return compressStreamBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Compress the stream transferred over MQTT
     * </pre>
     *
     * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
     */
    public Builder setCompressStream(com.google.protobuf.BoolValue value) {
      if (compressStreamBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        compressStream_ = value;
        onChanged();
      } else {
        compressStreamBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *Compress the stream transferred over MQTT
     * </pre>
     *
     * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
     */
    public Builder setCompressStream(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (compressStreamBuilder_ == null) {
        compressStream_ = builderForValue.build();
        onChanged();
      } else {
        compressStreamBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *Compress the stream transferred over MQTT
     * </pre>
     *
     * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
     */
    public Builder mergeCompressStream(com.google.protobuf.BoolValue value) {
      if (compressStreamBuilder_ == null) {
        if (compressStream_ != null) {
          compressStream_ =
            com.google.protobuf.BoolValue.newBuilder(compressStream_).mergeFrom(value).buildPartial();
        } else {
          compressStream_ = value;
        }
        onChanged();
      } else {
        compressStreamBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *Compress the stream transferred over MQTT
     * </pre>
     *
     * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
     */
    public Builder clearCompressStream() {
      if (compressStreamBuilder_ == null) {
        compressStream_ = null;
        onChanged();
      } else {
        compressStream_ = null;
        compressStreamBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *Compress the stream transferred over MQTT
     * </pre>
     *
     * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
     */
    public com.google.protobuf.BoolValue.Builder getCompressStreamBuilder() {
      
      onChanged();
      return getCompressStreamFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Compress the stream transferred over MQTT
     * </pre>
     *
     * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getCompressStreamOrBuilder() {
      if (compressStreamBuilder_ != null) {
        return compressStreamBuilder_.getMessageOrBuilder();
      } else {
        return compressStream_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : compressStream_;
      }
    }
    /**
     * <pre>
     *Compress the stream transferred over MQTT
     * </pre>
     *
     * <code>.google.protobuf.BoolValue compress_stream = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getCompressStreamFieldBuilder() {
      if (compressStreamBuilder_ == null) {
        compressStreamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getCompressStream(),
                getParentForChildren(),
                isClean());
        compressStream_ = null;
      }
      return compressStreamBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.Comms.ClientProto.FileStreamResponse)
  }

  // @@protoc_insertion_point(class_scope:WISE.Comms.ClientProto.FileStreamResponse)
  private static final ca.wise.comms.client.proto.FileStreamResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.comms.client.proto.FileStreamResponse();
  }

  public static ca.wise.comms.client.proto.FileStreamResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileStreamResponse>
      PARSER = new com.google.protobuf.AbstractParser<FileStreamResponse>() {
    @java.lang.Override
    public FileStreamResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileStreamResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileStreamResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileStreamResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.comms.client.proto.FileStreamResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

