// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto

package ca.wise.status.proto;

public interface jobStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.StatusProto.jobStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * The list of status and informational messages.
   * </pre>
   *
   * <code>repeated .WISE.StatusProto.jobStatus.statusEntry entries = 1;</code>
   */
  java.util.List<ca.wise.status.proto.jobStatus.statusEntry> 
      getEntriesList();
  /**
   * <pre>
   **
   * The list of status and informational messages.
   * </pre>
   *
   * <code>repeated .WISE.StatusProto.jobStatus.statusEntry entries = 1;</code>
   */
  ca.wise.status.proto.jobStatus.statusEntry getEntries(int index);
  /**
   * <pre>
   **
   * The list of status and informational messages.
   * </pre>
   *
   * <code>repeated .WISE.StatusProto.jobStatus.statusEntry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <pre>
   **
   * The list of status and informational messages.
   * </pre>
   *
   * <code>repeated .WISE.StatusProto.jobStatus.statusEntry entries = 1;</code>
   */
  java.util.List<? extends ca.wise.status.proto.jobStatus.statusEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <pre>
   **
   * The list of status and informational messages.
   * </pre>
   *
   * <code>repeated .WISE.StatusProto.jobStatus.statusEntry entries = 1;</code>
   */
  ca.wise.status.proto.jobStatus.statusEntryOrBuilder getEntriesOrBuilder(
      int index);
}
