// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation_report.proto

#include "validation_report.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_validation_5freport_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_ValidationReport_ValidationNode_validation_5freport_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_validation_5freport_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ValidationReport_ValidationNode_ErrorObject_validation_5freport_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fwrappers_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_StringValue_google_2fprotobuf_2fwrappers_2eproto;
namespace WISE {
namespace Comms {
namespace ValidationProto {
class ValidationReport_ValidationNode_ErrorObjectDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ValidationReport_ValidationNode_ErrorObject> _instance;
} _ValidationReport_ValidationNode_ErrorObject_default_instance_;
class ValidationReport_ValidationNodeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ValidationReport_ValidationNode> _instance;
} _ValidationReport_ValidationNode_default_instance_;
class ValidationReportDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ValidationReport> _instance;
} _ValidationReport_default_instance_;
}  // namespace ValidationProto
}  // namespace Comms
}  // namespace WISE
static void InitDefaultsscc_info_ValidationReport_validation_5freport_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::WISE::Comms::ValidationProto::_ValidationReport_default_instance_;
    new (ptr) ::WISE::Comms::ValidationProto::ValidationReport();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::WISE::Comms::ValidationProto::ValidationReport::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_ValidationReport_validation_5freport_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_ValidationReport_validation_5freport_2eproto}, {
      &scc_info_StringValue_google_2fprotobuf_2fwrappers_2eproto.base,
      &scc_info_ValidationReport_ValidationNode_validation_5freport_2eproto.base,}};

static void InitDefaultsscc_info_ValidationReport_ValidationNode_validation_5freport_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::WISE::Comms::ValidationProto::_ValidationReport_ValidationNode_default_instance_;
    new (ptr) ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_ValidationReport_ValidationNode_validation_5freport_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_ValidationReport_ValidationNode_validation_5freport_2eproto}, {
      &scc_info_ValidationReport_ValidationNode_ErrorObject_validation_5freport_2eproto.base,
      &scc_info_StringValue_google_2fprotobuf_2fwrappers_2eproto.base,}};

static void InitDefaultsscc_info_ValidationReport_ValidationNode_ErrorObject_validation_5freport_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::WISE::Comms::ValidationProto::_ValidationReport_ValidationNode_ErrorObject_default_instance_;
    new (ptr) ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorObject();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorObject::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ValidationReport_ValidationNode_ErrorObject_validation_5freport_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ValidationReport_ValidationNode_ErrorObject_validation_5freport_2eproto}, {
      &scc_info_StringValue_google_2fprotobuf_2fwrappers_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_validation_5freport_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_validation_5freport_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_validation_5freport_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_validation_5freport_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorObject, name_),
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorObject, value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode, error_level_),
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode, protobuf_name_),
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode, error_values_),
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode, error_id_),
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode, children_),
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode, details_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport, success_),
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport, valid_),
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport, load_warnings_),
  PROTOBUF_FIELD_OFFSET(::WISE::Comms::ValidationProto::ValidationReport, validation_tree_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorObject)},
  { 7, -1, sizeof(::WISE::Comms::ValidationProto::ValidationReport_ValidationNode)},
  { 18, -1, sizeof(::WISE::Comms::ValidationProto::ValidationReport)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::WISE::Comms::ValidationProto::_ValidationReport_ValidationNode_ErrorObject_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::WISE::Comms::ValidationProto::_ValidationReport_ValidationNode_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::WISE::Comms::ValidationProto::_ValidationReport_default_instance_),
};

const char descriptor_table_protodef_validation_5freport_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027validation_report.proto\022\032WISE.Comms.Va"
  "lidationProto\032\036google/protobuf/wrappers."
  "proto\"\335\005\n\020ValidationReport\022\017\n\007success\030\001 "
  "\001(\010\022\r\n\005valid\030\002 \001(\010\0223\n\rload_warnings\030\003 \001("
  "\0132\034.google.protobuf.StringValue\022T\n\017valid"
  "ation_tree\030\004 \001(\0132;.WISE.Comms.Validation"
  "Proto.ValidationReport.ValidationNode\032\235\004"
  "\n\016ValidationNode\022[\n\013error_level\030\001 \001(\0162F."
  "WISE.Comms.ValidationProto.ValidationRep"
  "ort.ValidationNode.ErrorLevel\022\025\n\rprotobu"
  "f_name\030\002 \001(\t\022]\n\014error_values\030\003 \003(\0132G.WIS"
  "E.Comms.ValidationProto.ValidationReport"
  ".ValidationNode.ErrorObject\022.\n\010error_id\030"
  "\004 \001(\0132\034.google.protobuf.StringValue\022M\n\010c"
  "hildren\030\005 \003(\0132;.WISE.Comms.ValidationPro"
  "to.ValidationReport.ValidationNode\022-\n\007de"
  "tails\030\006 \001(\0132\034.google.protobuf.StringValu"
  "e\032H\n\013ErrorObject\022\014\n\004name\030\001 \001(\t\022+\n\005value\030"
  "\002 \001(\0132\034.google.protobuf.StringValue\"@\n\nE"
  "rrorLevel\022\010\n\004NONE\020\000\022\017\n\013INFORMATION\020\001\022\013\n\007"
  "WARNING\020\002\022\n\n\006SEVERE\020\003B\036\n\032ca.wise.comms.s"
  "erver.protoP\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_validation_5freport_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_validation_5freport_2eproto_sccs[3] = {
  &scc_info_ValidationReport_validation_5freport_2eproto.base,
  &scc_info_ValidationReport_ValidationNode_validation_5freport_2eproto.base,
  &scc_info_ValidationReport_ValidationNode_ErrorObject_validation_5freport_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_validation_5freport_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_validation_5freport_2eproto = {
  false, false, descriptor_table_protodef_validation_5freport_2eproto, "validation_report.proto", 861,
  &descriptor_table_validation_5freport_2eproto_once, descriptor_table_validation_5freport_2eproto_sccs, descriptor_table_validation_5freport_2eproto_deps, 3, 1,
  schemas, file_default_instances, TableStruct_validation_5freport_2eproto::offsets,
  file_level_metadata_validation_5freport_2eproto, 3, file_level_enum_descriptors_validation_5freport_2eproto, file_level_service_descriptors_validation_5freport_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_validation_5freport_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_validation_5freport_2eproto)), true);
namespace WISE {
namespace Comms {
namespace ValidationProto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ValidationReport_ValidationNode_ErrorLevel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_validation_5freport_2eproto);
  return file_level_enum_descriptors_validation_5freport_2eproto[0];
}
bool ValidationReport_ValidationNode_ErrorLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ValidationReport_ValidationNode_ErrorLevel ValidationReport_ValidationNode::NONE;
constexpr ValidationReport_ValidationNode_ErrorLevel ValidationReport_ValidationNode::INFORMATION;
constexpr ValidationReport_ValidationNode_ErrorLevel ValidationReport_ValidationNode::WARNING;
constexpr ValidationReport_ValidationNode_ErrorLevel ValidationReport_ValidationNode::SEVERE;
constexpr ValidationReport_ValidationNode_ErrorLevel ValidationReport_ValidationNode::ErrorLevel_MIN;
constexpr ValidationReport_ValidationNode_ErrorLevel ValidationReport_ValidationNode::ErrorLevel_MAX;
constexpr int ValidationReport_ValidationNode::ErrorLevel_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void ValidationReport_ValidationNode_ErrorObject::InitAsDefaultInstance() {
  ::WISE::Comms::ValidationProto::_ValidationReport_ValidationNode_ErrorObject_default_instance_._instance.get_mutable()->value_ = const_cast< PROTOBUF_NAMESPACE_ID::StringValue*>(
      PROTOBUF_NAMESPACE_ID::StringValue::internal_default_instance());
}
class ValidationReport_ValidationNode_ErrorObject::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::StringValue& value(const ValidationReport_ValidationNode_ErrorObject* msg);
};

const PROTOBUF_NAMESPACE_ID::StringValue&
ValidationReport_ValidationNode_ErrorObject::_Internal::value(const ValidationReport_ValidationNode_ErrorObject* msg) {
  return *msg->value_;
}
void ValidationReport_ValidationNode_ErrorObject::clear_value() {
  if (GetArena() == nullptr && value_ != nullptr) {
    delete value_;
  }
  value_ = nullptr;
}
ValidationReport_ValidationNode_ErrorObject::ValidationReport_ValidationNode_ErrorObject(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
}
ValidationReport_ValidationNode_ErrorObject::ValidationReport_ValidationNode_ErrorObject(const ValidationReport_ValidationNode_ErrorObject& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  if (from._internal_has_value()) {
    value_ = new PROTOBUF_NAMESPACE_ID::StringValue(*from.value_);
  } else {
    value_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
}

void ValidationReport_ValidationNode_ErrorObject::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ValidationReport_ValidationNode_ErrorObject_validation_5freport_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  value_ = nullptr;
}

ValidationReport_ValidationNode_ErrorObject::~ValidationReport_ValidationNode_ErrorObject() {
  // @@protoc_insertion_point(destructor:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ValidationReport_ValidationNode_ErrorObject::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete value_;
}

void ValidationReport_ValidationNode_ErrorObject::ArenaDtor(void* object) {
  ValidationReport_ValidationNode_ErrorObject* _this = reinterpret_cast< ValidationReport_ValidationNode_ErrorObject* >(object);
  (void)_this;
}
void ValidationReport_ValidationNode_ErrorObject::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ValidationReport_ValidationNode_ErrorObject::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ValidationReport_ValidationNode_ErrorObject& ValidationReport_ValidationNode_ErrorObject::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ValidationReport_ValidationNode_ErrorObject_validation_5freport_2eproto.base);
  return *internal_default_instance();
}


void ValidationReport_ValidationNode_ErrorObject::Clear() {
// @@protoc_insertion_point(message_clear_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && value_ != nullptr) {
    delete value_;
  }
  value_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ValidationReport_ValidationNode_ErrorObject::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.StringValue value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ValidationReport_ValidationNode_ErrorObject::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // .google.protobuf.StringValue value = 2;
  if (this->has_value()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::value(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
  return target;
}

size_t ValidationReport_ValidationNode_ErrorObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // .google.protobuf.StringValue value = 2;
  if (this->has_value()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *value_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ValidationReport_ValidationNode_ErrorObject::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
  GOOGLE_DCHECK_NE(&from, this);
  const ValidationReport_ValidationNode_ErrorObject* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ValidationReport_ValidationNode_ErrorObject>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
    MergeFrom(*source);
  }
}

void ValidationReport_ValidationNode_ErrorObject::MergeFrom(const ValidationReport_ValidationNode_ErrorObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
  if (from.has_value()) {
    _internal_mutable_value()->PROTOBUF_NAMESPACE_ID::StringValue::MergeFrom(from._internal_value());
  }
}

void ValidationReport_ValidationNode_ErrorObject::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ValidationReport_ValidationNode_ErrorObject::CopyFrom(const ValidationReport_ValidationNode_ErrorObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ValidationReport_ValidationNode_ErrorObject::IsInitialized() const {
  return true;
}

void ValidationReport_ValidationNode_ErrorObject::InternalSwap(ValidationReport_ValidationNode_ErrorObject* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(value_, other->value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ValidationReport_ValidationNode_ErrorObject::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ValidationReport_ValidationNode::InitAsDefaultInstance() {
  ::WISE::Comms::ValidationProto::_ValidationReport_ValidationNode_default_instance_._instance.get_mutable()->error_id_ = const_cast< PROTOBUF_NAMESPACE_ID::StringValue*>(
      PROTOBUF_NAMESPACE_ID::StringValue::internal_default_instance());
  ::WISE::Comms::ValidationProto::_ValidationReport_ValidationNode_default_instance_._instance.get_mutable()->details_ = const_cast< PROTOBUF_NAMESPACE_ID::StringValue*>(
      PROTOBUF_NAMESPACE_ID::StringValue::internal_default_instance());
}
class ValidationReport_ValidationNode::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::StringValue& error_id(const ValidationReport_ValidationNode* msg);
  static const PROTOBUF_NAMESPACE_ID::StringValue& details(const ValidationReport_ValidationNode* msg);
};

const PROTOBUF_NAMESPACE_ID::StringValue&
ValidationReport_ValidationNode::_Internal::error_id(const ValidationReport_ValidationNode* msg) {
  return *msg->error_id_;
}
const PROTOBUF_NAMESPACE_ID::StringValue&
ValidationReport_ValidationNode::_Internal::details(const ValidationReport_ValidationNode* msg) {
  return *msg->details_;
}
void ValidationReport_ValidationNode::clear_error_id() {
  if (GetArena() == nullptr && error_id_ != nullptr) {
    delete error_id_;
  }
  error_id_ = nullptr;
}
void ValidationReport_ValidationNode::clear_details() {
  if (GetArena() == nullptr && details_ != nullptr) {
    delete details_;
  }
  details_ = nullptr;
}
ValidationReport_ValidationNode::ValidationReport_ValidationNode(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  error_values_(arena),
  children_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
}
ValidationReport_ValidationNode::ValidationReport_ValidationNode(const ValidationReport_ValidationNode& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      error_values_(from.error_values_),
      children_(from.children_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  protobuf_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_protobuf_name().empty()) {
    protobuf_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_protobuf_name(),
      GetArena());
  }
  if (from._internal_has_error_id()) {
    error_id_ = new PROTOBUF_NAMESPACE_ID::StringValue(*from.error_id_);
  } else {
    error_id_ = nullptr;
  }
  if (from._internal_has_details()) {
    details_ = new PROTOBUF_NAMESPACE_ID::StringValue(*from.details_);
  } else {
    details_ = nullptr;
  }
  error_level_ = from.error_level_;
  // @@protoc_insertion_point(copy_constructor:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
}

void ValidationReport_ValidationNode::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ValidationReport_ValidationNode_validation_5freport_2eproto.base);
  protobuf_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&error_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&error_level_) -
      reinterpret_cast<char*>(&error_id_)) + sizeof(error_level_));
}

ValidationReport_ValidationNode::~ValidationReport_ValidationNode() {
  // @@protoc_insertion_point(destructor:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ValidationReport_ValidationNode::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  protobuf_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete error_id_;
  if (this != internal_default_instance()) delete details_;
}

void ValidationReport_ValidationNode::ArenaDtor(void* object) {
  ValidationReport_ValidationNode* _this = reinterpret_cast< ValidationReport_ValidationNode* >(object);
  (void)_this;
}
void ValidationReport_ValidationNode::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ValidationReport_ValidationNode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ValidationReport_ValidationNode& ValidationReport_ValidationNode::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ValidationReport_ValidationNode_validation_5freport_2eproto.base);
  return *internal_default_instance();
}


void ValidationReport_ValidationNode::Clear() {
// @@protoc_insertion_point(message_clear_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  error_values_.Clear();
  children_.Clear();
  protobuf_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  if (GetArena() == nullptr && error_id_ != nullptr) {
    delete error_id_;
  }
  error_id_ = nullptr;
  if (GetArena() == nullptr && details_ != nullptr) {
    delete details_;
  }
  details_ = nullptr;
  error_level_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ValidationReport_ValidationNode::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorLevel error_level = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_error_level(static_cast<::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorLevel>(val));
        } else goto handle_unusual;
        continue;
      // string protobuf_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_protobuf_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "WISE.Comms.ValidationProto.ValidationReport.ValidationNode.protobuf_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject error_values = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_error_values(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // .google.protobuf.StringValue error_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_error_id(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .WISE.Comms.ValidationProto.ValidationReport.ValidationNode children = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_children(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      // .google.protobuf.StringValue details = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_details(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ValidationReport_ValidationNode::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorLevel error_level = 1;
  if (this->error_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_error_level(), target);
  }

  // string protobuf_name = 2;
  if (this->protobuf_name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_protobuf_name().data(), static_cast<int>(this->_internal_protobuf_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "WISE.Comms.ValidationProto.ValidationReport.ValidationNode.protobuf_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_protobuf_name(), target);
  }

  // repeated .WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject error_values = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_error_values_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_error_values(i), target, stream);
  }

  // .google.protobuf.StringValue error_id = 4;
  if (this->has_error_id()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::error_id(this), target, stream);
  }

  // repeated .WISE.Comms.ValidationProto.ValidationReport.ValidationNode children = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_children_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, this->_internal_children(i), target, stream);
  }

  // .google.protobuf.StringValue details = 6;
  if (this->has_details()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::details(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
  return target;
}

size_t ValidationReport_ValidationNode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorObject error_values = 3;
  total_size += 1UL * this->_internal_error_values_size();
  for (const auto& msg : this->error_values_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .WISE.Comms.ValidationProto.ValidationReport.ValidationNode children = 5;
  total_size += 1UL * this->_internal_children_size();
  for (const auto& msg : this->children_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string protobuf_name = 2;
  if (this->protobuf_name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_protobuf_name());
  }

  // .google.protobuf.StringValue error_id = 4;
  if (this->has_error_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *error_id_);
  }

  // .google.protobuf.StringValue details = 6;
  if (this->has_details()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *details_);
  }

  // .WISE.Comms.ValidationProto.ValidationReport.ValidationNode.ErrorLevel error_level = 1;
  if (this->error_level() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_error_level());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ValidationReport_ValidationNode::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
  GOOGLE_DCHECK_NE(&from, this);
  const ValidationReport_ValidationNode* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ValidationReport_ValidationNode>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
    MergeFrom(*source);
  }
}

void ValidationReport_ValidationNode::MergeFrom(const ValidationReport_ValidationNode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  error_values_.MergeFrom(from.error_values_);
  children_.MergeFrom(from.children_);
  if (from.protobuf_name().size() > 0) {
    _internal_set_protobuf_name(from._internal_protobuf_name());
  }
  if (from.has_error_id()) {
    _internal_mutable_error_id()->PROTOBUF_NAMESPACE_ID::StringValue::MergeFrom(from._internal_error_id());
  }
  if (from.has_details()) {
    _internal_mutable_details()->PROTOBUF_NAMESPACE_ID::StringValue::MergeFrom(from._internal_details());
  }
  if (from.error_level() != 0) {
    _internal_set_error_level(from._internal_error_level());
  }
}

void ValidationReport_ValidationNode::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ValidationReport_ValidationNode::CopyFrom(const ValidationReport_ValidationNode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WISE.Comms.ValidationProto.ValidationReport.ValidationNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ValidationReport_ValidationNode::IsInitialized() const {
  return true;
}

void ValidationReport_ValidationNode::InternalSwap(ValidationReport_ValidationNode* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  error_values_.InternalSwap(&other->error_values_);
  children_.InternalSwap(&other->children_);
  protobuf_name_.Swap(&other->protobuf_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ValidationReport_ValidationNode, error_level_)
      + sizeof(ValidationReport_ValidationNode::error_level_)
      - PROTOBUF_FIELD_OFFSET(ValidationReport_ValidationNode, error_id_)>(
          reinterpret_cast<char*>(&error_id_),
          reinterpret_cast<char*>(&other->error_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ValidationReport_ValidationNode::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ValidationReport::InitAsDefaultInstance() {
  ::WISE::Comms::ValidationProto::_ValidationReport_default_instance_._instance.get_mutable()->load_warnings_ = const_cast< PROTOBUF_NAMESPACE_ID::StringValue*>(
      PROTOBUF_NAMESPACE_ID::StringValue::internal_default_instance());
  ::WISE::Comms::ValidationProto::_ValidationReport_default_instance_._instance.get_mutable()->validation_tree_ = const_cast< ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode*>(
      ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode::internal_default_instance());
}
class ValidationReport::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::StringValue& load_warnings(const ValidationReport* msg);
  static const ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode& validation_tree(const ValidationReport* msg);
};

const PROTOBUF_NAMESPACE_ID::StringValue&
ValidationReport::_Internal::load_warnings(const ValidationReport* msg) {
  return *msg->load_warnings_;
}
const ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode&
ValidationReport::_Internal::validation_tree(const ValidationReport* msg) {
  return *msg->validation_tree_;
}
void ValidationReport::clear_load_warnings() {
  if (GetArena() == nullptr && load_warnings_ != nullptr) {
    delete load_warnings_;
  }
  load_warnings_ = nullptr;
}
ValidationReport::ValidationReport(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:WISE.Comms.ValidationProto.ValidationReport)
}
ValidationReport::ValidationReport(const ValidationReport& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_load_warnings()) {
    load_warnings_ = new PROTOBUF_NAMESPACE_ID::StringValue(*from.load_warnings_);
  } else {
    load_warnings_ = nullptr;
  }
  if (from._internal_has_validation_tree()) {
    validation_tree_ = new ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode(*from.validation_tree_);
  } else {
    validation_tree_ = nullptr;
  }
  ::memcpy(&success_, &from.success_,
    static_cast<size_t>(reinterpret_cast<char*>(&valid_) -
    reinterpret_cast<char*>(&success_)) + sizeof(valid_));
  // @@protoc_insertion_point(copy_constructor:WISE.Comms.ValidationProto.ValidationReport)
}

void ValidationReport::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ValidationReport_validation_5freport_2eproto.base);
  ::memset(&load_warnings_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&valid_) -
      reinterpret_cast<char*>(&load_warnings_)) + sizeof(valid_));
}

ValidationReport::~ValidationReport() {
  // @@protoc_insertion_point(destructor:WISE.Comms.ValidationProto.ValidationReport)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ValidationReport::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete load_warnings_;
  if (this != internal_default_instance()) delete validation_tree_;
}

void ValidationReport::ArenaDtor(void* object) {
  ValidationReport* _this = reinterpret_cast< ValidationReport* >(object);
  (void)_this;
}
void ValidationReport::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ValidationReport::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ValidationReport& ValidationReport::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ValidationReport_validation_5freport_2eproto.base);
  return *internal_default_instance();
}


void ValidationReport::Clear() {
// @@protoc_insertion_point(message_clear_start:WISE.Comms.ValidationProto.ValidationReport)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && load_warnings_ != nullptr) {
    delete load_warnings_;
  }
  load_warnings_ = nullptr;
  if (GetArena() == nullptr && validation_tree_ != nullptr) {
    delete validation_tree_;
  }
  validation_tree_ = nullptr;
  ::memset(&success_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&valid_) -
      reinterpret_cast<char*>(&success_)) + sizeof(valid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ValidationReport::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool valid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          valid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.StringValue load_warnings = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_load_warnings(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .WISE.Comms.ValidationProto.ValidationReport.ValidationNode validation_tree = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_validation_tree(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ValidationReport::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:WISE.Comms.ValidationProto.ValidationReport)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // bool valid = 2;
  if (this->valid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_valid(), target);
  }

  // .google.protobuf.StringValue load_warnings = 3;
  if (this->has_load_warnings()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::load_warnings(this), target, stream);
  }

  // .WISE.Comms.ValidationProto.ValidationReport.ValidationNode validation_tree = 4;
  if (this->has_validation_tree()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::validation_tree(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WISE.Comms.ValidationProto.ValidationReport)
  return target;
}

size_t ValidationReport::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WISE.Comms.ValidationProto.ValidationReport)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.StringValue load_warnings = 3;
  if (this->has_load_warnings()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *load_warnings_);
  }

  // .WISE.Comms.ValidationProto.ValidationReport.ValidationNode validation_tree = 4;
  if (this->has_validation_tree()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *validation_tree_);
  }

  // bool success = 1;
  if (this->success() != 0) {
    total_size += 1 + 1;
  }

  // bool valid = 2;
  if (this->valid() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ValidationReport::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:WISE.Comms.ValidationProto.ValidationReport)
  GOOGLE_DCHECK_NE(&from, this);
  const ValidationReport* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ValidationReport>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:WISE.Comms.ValidationProto.ValidationReport)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:WISE.Comms.ValidationProto.ValidationReport)
    MergeFrom(*source);
  }
}

void ValidationReport::MergeFrom(const ValidationReport& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:WISE.Comms.ValidationProto.ValidationReport)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_load_warnings()) {
    _internal_mutable_load_warnings()->PROTOBUF_NAMESPACE_ID::StringValue::MergeFrom(from._internal_load_warnings());
  }
  if (from.has_validation_tree()) {
    _internal_mutable_validation_tree()->::WISE::Comms::ValidationProto::ValidationReport_ValidationNode::MergeFrom(from._internal_validation_tree());
  }
  if (from.success() != 0) {
    _internal_set_success(from._internal_success());
  }
  if (from.valid() != 0) {
    _internal_set_valid(from._internal_valid());
  }
}

void ValidationReport::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:WISE.Comms.ValidationProto.ValidationReport)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ValidationReport::CopyFrom(const ValidationReport& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WISE.Comms.ValidationProto.ValidationReport)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ValidationReport::IsInitialized() const {
  return true;
}

void ValidationReport::InternalSwap(ValidationReport* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ValidationReport, valid_)
      + sizeof(ValidationReport::valid_)
      - PROTOBUF_FIELD_OFFSET(ValidationReport, load_warnings_)>(
          reinterpret_cast<char*>(&load_warnings_),
          reinterpret_cast<char*>(&other->load_warnings_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ValidationReport::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ValidationProto
}  // namespace Comms
}  // namespace WISE
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorObject* Arena::CreateMaybeMessage< ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorObject >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode_ErrorObject >(arena);
}
template<> PROTOBUF_NOINLINE ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode* Arena::CreateMaybeMessage< ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WISE::Comms::ValidationProto::ValidationReport_ValidationNode >(arena);
}
template<> PROTOBUF_NOINLINE ::WISE::Comms::ValidationProto::ValidationReport* Arena::CreateMaybeMessage< ::WISE::Comms::ValidationProto::ValidationReport >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WISE::Comms::ValidationProto::ValidationReport >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
