// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.server.proto;

public interface FileUploadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.Comms.ServerProto.FileUpload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *The name of the job that the file is for.
   *Will be used to find the correct receiver as well as to find the file in the job directory.
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The job.
   */
  java.lang.String getJob();
  /**
   * <pre>
   *The name of the job that the file is for.
   *Will be used to find the correct receiver as well as to find the file in the job directory.
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The bytes for job.
   */
  com.google.protobuf.ByteString
      getJobBytes();

  /**
   * <pre>
   *The name of the file to upload, including all subfolders within the jobs folder.
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <pre>
   *The name of the file to upload, including all subfolders within the jobs folder.
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  java.util.List<ca.wise.comms.server.proto.FileUpload.UploadType> 
      getUploadTypeList();
  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  ca.wise.comms.server.proto.FileUpload.UploadType getUploadType(int index);
  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  int getUploadTypeCount();
  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  java.util.List<? extends ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder> 
      getUploadTypeOrBuilderList();
  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder getUploadTypeOrBuilder(
      int index);

  /**
   * <pre>
   *The type of file to upload
   * </pre>
   *
   * <code>.WISE.Comms.ServerProto.FileUpload.FileType filetype = 4;</code>
   * @return The enum numeric value on the wire for filetype.
   */
  int getFiletypeValue();
  /**
   * <pre>
   *The type of file to upload
   * </pre>
   *
   * <code>.WISE.Comms.ServerProto.FileUpload.FileType filetype = 4;</code>
   * @return The filetype.
   */
  ca.wise.comms.server.proto.FileUpload.FileType getFiletype();

  /**
   * <pre>
   *Does the file exist or was it skipped because it would be empty
   * </pre>
   *
   * <code>bool exists = 5;</code>
   * @return The exists.
   */
  boolean getExists();
}
