// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.server.proto;

/**
 * <pre>
 **
 * A wrapper around a file upload request from W.I.S.E.
 * to W.I.S.E. Manager.
 * </pre>
 *
 * Protobuf type {@code WISE.Comms.ServerProto.FileUpload}
 */
public final class FileUpload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.Comms.ServerProto.FileUpload)
    FileUploadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileUpload.newBuilder() to construct.
  private FileUpload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileUpload() {
    job_ = "";
    filename_ = "";
    uploadType_ = java.util.Collections.emptyList();
    filetype_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileUpload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileUpload(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            job_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            filename_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              uploadType_ = new java.util.ArrayList<ca.wise.comms.server.proto.FileUpload.UploadType>();
              mutable_bitField0_ |= 0x00000001;
            }
            uploadType_.add(
                input.readMessage(ca.wise.comms.server.proto.FileUpload.UploadType.parser(), extensionRegistry));
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            filetype_ = rawValue;
            break;
          }
          case 40: {

            exists_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        uploadType_ = java.util.Collections.unmodifiableList(uploadType_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.comms.server.proto.FileUpload.class, ca.wise.comms.server.proto.FileUpload.Builder.class);
  }

  /**
   * Protobuf enum {@code WISE.Comms.ServerProto.FileUpload.FileType}
   */
  public enum FileType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unknown = 0;</code>
     */
    Unknown(0),
    /**
     * <code>Summary = 1;</code>
     */
    Summary(1),
    /**
     * <code>Vector = 2;</code>
     */
    Vector(2),
    /**
     * <code>Grid = 3;</code>
     */
    Grid(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Unknown = 0;</code>
     */
    public static final int Unknown_VALUE = 0;
    /**
     * <code>Summary = 1;</code>
     */
    public static final int Summary_VALUE = 1;
    /**
     * <code>Vector = 2;</code>
     */
    public static final int Vector_VALUE = 2;
    /**
     * <code>Grid = 3;</code>
     */
    public static final int Grid_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FileType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FileType forNumber(int value) {
      switch (value) {
        case 0: return Unknown;
        case 1: return Summary;
        case 2: return Vector;
        case 3: return Grid;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FileType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FileType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
            public FileType findValueByNumber(int number) {
              return FileType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ca.wise.comms.server.proto.FileUpload.getDescriptor().getEnumTypes().get(0);
    }

    private static final FileType[] VALUES = values();

    public static FileType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FileType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WISE.Comms.ServerProto.FileUpload.FileType)
  }

  public interface UploadTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WISE.Comms.ServerProto.FileUpload.UploadType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
     * @return Whether the mqtt field is set.
     */
    boolean hasMqtt();
    /**
     * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
     * @return The mqtt.
     */
    ca.wise.comms.server.proto.MQTTUpload getMqtt();
    /**
     * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
     */
    ca.wise.comms.server.proto.MQTTUploadOrBuilder getMqttOrBuilder();

    /**
     * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
     * @return Whether the geoserver field is set.
     */
    boolean hasGeoserver();
    /**
     * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
     * @return The geoserver.
     */
    ca.wise.comms.server.proto.GeoserverUpload getGeoserver();
    /**
     * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
     */
    ca.wise.comms.server.proto.GeoserverUploadOrBuilder getGeoserverOrBuilder();

    public ca.wise.comms.server.proto.FileUpload.UploadType.TypeCase getTypeCase();
  }
  /**
   * <pre>
   *Information about the file upload.
   * </pre>
   *
   * Protobuf type {@code WISE.Comms.ServerProto.FileUpload.UploadType}
   */
  public static final class UploadType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WISE.Comms.ServerProto.FileUpload.UploadType)
      UploadTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadType.newBuilder() to construct.
    private UploadType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadType() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UploadType();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ca.wise.comms.server.proto.MQTTUpload.Builder subBuilder = null;
              if (typeCase_ == 1) {
                subBuilder = ((ca.wise.comms.server.proto.MQTTUpload) type_).toBuilder();
              }
              type_ =
                  input.readMessage(ca.wise.comms.server.proto.MQTTUpload.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ca.wise.comms.server.proto.MQTTUpload) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 1;
              break;
            }
            case 18: {
              ca.wise.comms.server.proto.GeoserverUpload.Builder subBuilder = null;
              if (typeCase_ == 2) {
                subBuilder = ((ca.wise.comms.server.proto.GeoserverUpload) type_).toBuilder();
              }
              type_ =
                  input.readMessage(ca.wise.comms.server.proto.GeoserverUpload.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ca.wise.comms.server.proto.GeoserverUpload) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.comms.server.proto.FileUpload.UploadType.class, ca.wise.comms.server.proto.FileUpload.UploadType.Builder.class);
    }

    private int typeCase_ = 0;
    private java.lang.Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      MQTT(1),
      GEOSERVER(2),
      TYPE_NOT_SET(0);
      private final int value;
      private TypeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeCase forNumber(int value) {
        switch (value) {
          case 1: return MQTT;
          case 2: return GEOSERVER;
          case 0: return TYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    public static final int MQTT_FIELD_NUMBER = 1;
    /**
     * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
     * @return Whether the mqtt field is set.
     */
    @java.lang.Override
    public boolean hasMqtt() {
      return typeCase_ == 1;
    }
    /**
     * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
     * @return The mqtt.
     */
    @java.lang.Override
    public ca.wise.comms.server.proto.MQTTUpload getMqtt() {
      if (typeCase_ == 1) {
         return (ca.wise.comms.server.proto.MQTTUpload) type_;
      }
      return ca.wise.comms.server.proto.MQTTUpload.getDefaultInstance();
    }
    /**
     * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
     */
    @java.lang.Override
    public ca.wise.comms.server.proto.MQTTUploadOrBuilder getMqttOrBuilder() {
      if (typeCase_ == 1) {
         return (ca.wise.comms.server.proto.MQTTUpload) type_;
      }
      return ca.wise.comms.server.proto.MQTTUpload.getDefaultInstance();
    }

    public static final int GEOSERVER_FIELD_NUMBER = 2;
    /**
     * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
     * @return Whether the geoserver field is set.
     */
    @java.lang.Override
    public boolean hasGeoserver() {
      return typeCase_ == 2;
    }
    /**
     * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
     * @return The geoserver.
     */
    @java.lang.Override
    public ca.wise.comms.server.proto.GeoserverUpload getGeoserver() {
      if (typeCase_ == 2) {
         return (ca.wise.comms.server.proto.GeoserverUpload) type_;
      }
      return ca.wise.comms.server.proto.GeoserverUpload.getDefaultInstance();
    }
    /**
     * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
     */
    @java.lang.Override
    public ca.wise.comms.server.proto.GeoserverUploadOrBuilder getGeoserverOrBuilder() {
      if (typeCase_ == 2) {
         return (ca.wise.comms.server.proto.GeoserverUpload) type_;
      }
      return ca.wise.comms.server.proto.GeoserverUpload.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeCase_ == 1) {
        output.writeMessage(1, (ca.wise.comms.server.proto.MQTTUpload) type_);
      }
      if (typeCase_ == 2) {
        output.writeMessage(2, (ca.wise.comms.server.proto.GeoserverUpload) type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (typeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (ca.wise.comms.server.proto.MQTTUpload) type_);
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ca.wise.comms.server.proto.GeoserverUpload) type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.wise.comms.server.proto.FileUpload.UploadType)) {
        return super.equals(obj);
      }
      ca.wise.comms.server.proto.FileUpload.UploadType other = (ca.wise.comms.server.proto.FileUpload.UploadType) obj;

      if (!getTypeCase().equals(other.getTypeCase())) return false;
      switch (typeCase_) {
        case 1:
          if (!getMqtt()
              .equals(other.getMqtt())) return false;
          break;
        case 2:
          if (!getGeoserver()
              .equals(other.getGeoserver())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (typeCase_) {
        case 1:
          hash = (37 * hash) + MQTT_FIELD_NUMBER;
          hash = (53 * hash) + getMqtt().hashCode();
          break;
        case 2:
          hash = (37 * hash) + GEOSERVER_FIELD_NUMBER;
          hash = (53 * hash) + getGeoserver().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.wise.comms.server.proto.FileUpload.UploadType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.wise.comms.server.proto.FileUpload.UploadType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Information about the file upload.
     * </pre>
     *
     * Protobuf type {@code WISE.Comms.ServerProto.FileUpload.UploadType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WISE.Comms.ServerProto.FileUpload.UploadType)
        ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.wise.comms.server.proto.FileUpload.UploadType.class, ca.wise.comms.server.proto.FileUpload.UploadType.Builder.class);
      }

      // Construct using ca.wise.comms.server.proto.FileUpload.UploadType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        typeCase_ = 0;
        type_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_descriptor;
      }

      @java.lang.Override
      public ca.wise.comms.server.proto.FileUpload.UploadType getDefaultInstanceForType() {
        return ca.wise.comms.server.proto.FileUpload.UploadType.getDefaultInstance();
      }

      @java.lang.Override
      public ca.wise.comms.server.proto.FileUpload.UploadType build() {
        ca.wise.comms.server.proto.FileUpload.UploadType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.wise.comms.server.proto.FileUpload.UploadType buildPartial() {
        ca.wise.comms.server.proto.FileUpload.UploadType result = new ca.wise.comms.server.proto.FileUpload.UploadType(this);
        if (typeCase_ == 1) {
          if (mqttBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = mqttBuilder_.build();
          }
        }
        if (typeCase_ == 2) {
          if (geoserverBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = geoserverBuilder_.build();
          }
        }
        result.typeCase_ = typeCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.wise.comms.server.proto.FileUpload.UploadType) {
          return mergeFrom((ca.wise.comms.server.proto.FileUpload.UploadType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.wise.comms.server.proto.FileUpload.UploadType other) {
        if (other == ca.wise.comms.server.proto.FileUpload.UploadType.getDefaultInstance()) return this;
        switch (other.getTypeCase()) {
          case MQTT: {
            mergeMqtt(other.getMqtt());
            break;
          }
          case GEOSERVER: {
            mergeGeoserver(other.getGeoserver());
            break;
          }
          case TYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.wise.comms.server.proto.FileUpload.UploadType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.wise.comms.server.proto.FileUpload.UploadType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int typeCase_ = 0;
      private java.lang.Object type_;
      public TypeCase
          getTypeCase() {
        return TypeCase.forNumber(
            typeCase_);
      }

      public Builder clearType() {
        typeCase_ = 0;
        type_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.comms.server.proto.MQTTUpload, ca.wise.comms.server.proto.MQTTUpload.Builder, ca.wise.comms.server.proto.MQTTUploadOrBuilder> mqttBuilder_;
      /**
       * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
       * @return Whether the mqtt field is set.
       */
      @java.lang.Override
      public boolean hasMqtt() {
        return typeCase_ == 1;
      }
      /**
       * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
       * @return The mqtt.
       */
      @java.lang.Override
      public ca.wise.comms.server.proto.MQTTUpload getMqtt() {
        if (mqttBuilder_ == null) {
          if (typeCase_ == 1) {
            return (ca.wise.comms.server.proto.MQTTUpload) type_;
          }
          return ca.wise.comms.server.proto.MQTTUpload.getDefaultInstance();
        } else {
          if (typeCase_ == 1) {
            return mqttBuilder_.getMessage();
          }
          return ca.wise.comms.server.proto.MQTTUpload.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
       */
      public Builder setMqtt(ca.wise.comms.server.proto.MQTTUpload value) {
        if (mqttBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          mqttBuilder_.setMessage(value);
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
       */
      public Builder setMqtt(
          ca.wise.comms.server.proto.MQTTUpload.Builder builderForValue) {
        if (mqttBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          mqttBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
       */
      public Builder mergeMqtt(ca.wise.comms.server.proto.MQTTUpload value) {
        if (mqttBuilder_ == null) {
          if (typeCase_ == 1 &&
              type_ != ca.wise.comms.server.proto.MQTTUpload.getDefaultInstance()) {
            type_ = ca.wise.comms.server.proto.MQTTUpload.newBuilder((ca.wise.comms.server.proto.MQTTUpload) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 1) {
            mqttBuilder_.mergeFrom(value);
          }
          mqttBuilder_.setMessage(value);
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
       */
      public Builder clearMqtt() {
        if (mqttBuilder_ == null) {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
          }
          mqttBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
       */
      public ca.wise.comms.server.proto.MQTTUpload.Builder getMqttBuilder() {
        return getMqttFieldBuilder().getBuilder();
      }
      /**
       * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
       */
      @java.lang.Override
      public ca.wise.comms.server.proto.MQTTUploadOrBuilder getMqttOrBuilder() {
        if ((typeCase_ == 1) && (mqttBuilder_ != null)) {
          return mqttBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 1) {
            return (ca.wise.comms.server.proto.MQTTUpload) type_;
          }
          return ca.wise.comms.server.proto.MQTTUpload.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.Comms.ServerProto.MQTTUpload mqtt = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.comms.server.proto.MQTTUpload, ca.wise.comms.server.proto.MQTTUpload.Builder, ca.wise.comms.server.proto.MQTTUploadOrBuilder> 
          getMqttFieldBuilder() {
        if (mqttBuilder_ == null) {
          if (!(typeCase_ == 1)) {
            type_ = ca.wise.comms.server.proto.MQTTUpload.getDefaultInstance();
          }
          mqttBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.wise.comms.server.proto.MQTTUpload, ca.wise.comms.server.proto.MQTTUpload.Builder, ca.wise.comms.server.proto.MQTTUploadOrBuilder>(
                  (ca.wise.comms.server.proto.MQTTUpload) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 1;
        onChanged();;
        return mqttBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.comms.server.proto.GeoserverUpload, ca.wise.comms.server.proto.GeoserverUpload.Builder, ca.wise.comms.server.proto.GeoserverUploadOrBuilder> geoserverBuilder_;
      /**
       * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
       * @return Whether the geoserver field is set.
       */
      @java.lang.Override
      public boolean hasGeoserver() {
        return typeCase_ == 2;
      }
      /**
       * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
       * @return The geoserver.
       */
      @java.lang.Override
      public ca.wise.comms.server.proto.GeoserverUpload getGeoserver() {
        if (geoserverBuilder_ == null) {
          if (typeCase_ == 2) {
            return (ca.wise.comms.server.proto.GeoserverUpload) type_;
          }
          return ca.wise.comms.server.proto.GeoserverUpload.getDefaultInstance();
        } else {
          if (typeCase_ == 2) {
            return geoserverBuilder_.getMessage();
          }
          return ca.wise.comms.server.proto.GeoserverUpload.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
       */
      public Builder setGeoserver(ca.wise.comms.server.proto.GeoserverUpload value) {
        if (geoserverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          geoserverBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
       */
      public Builder setGeoserver(
          ca.wise.comms.server.proto.GeoserverUpload.Builder builderForValue) {
        if (geoserverBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          geoserverBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
       */
      public Builder mergeGeoserver(ca.wise.comms.server.proto.GeoserverUpload value) {
        if (geoserverBuilder_ == null) {
          if (typeCase_ == 2 &&
              type_ != ca.wise.comms.server.proto.GeoserverUpload.getDefaultInstance()) {
            type_ = ca.wise.comms.server.proto.GeoserverUpload.newBuilder((ca.wise.comms.server.proto.GeoserverUpload) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 2) {
            geoserverBuilder_.mergeFrom(value);
          }
          geoserverBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
       */
      public Builder clearGeoserver() {
        if (geoserverBuilder_ == null) {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
          }
          geoserverBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
       */
      public ca.wise.comms.server.proto.GeoserverUpload.Builder getGeoserverBuilder() {
        return getGeoserverFieldBuilder().getBuilder();
      }
      /**
       * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
       */
      @java.lang.Override
      public ca.wise.comms.server.proto.GeoserverUploadOrBuilder getGeoserverOrBuilder() {
        if ((typeCase_ == 2) && (geoserverBuilder_ != null)) {
          return geoserverBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 2) {
            return (ca.wise.comms.server.proto.GeoserverUpload) type_;
          }
          return ca.wise.comms.server.proto.GeoserverUpload.getDefaultInstance();
        }
      }
      /**
       * <code>.WISE.Comms.ServerProto.GeoserverUpload geoserver = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.wise.comms.server.proto.GeoserverUpload, ca.wise.comms.server.proto.GeoserverUpload.Builder, ca.wise.comms.server.proto.GeoserverUploadOrBuilder> 
          getGeoserverFieldBuilder() {
        if (geoserverBuilder_ == null) {
          if (!(typeCase_ == 2)) {
            type_ = ca.wise.comms.server.proto.GeoserverUpload.getDefaultInstance();
          }
          geoserverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.wise.comms.server.proto.GeoserverUpload, ca.wise.comms.server.proto.GeoserverUpload.Builder, ca.wise.comms.server.proto.GeoserverUploadOrBuilder>(
                  (ca.wise.comms.server.proto.GeoserverUpload) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 2;
        onChanged();;
        return geoserverBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WISE.Comms.ServerProto.FileUpload.UploadType)
    }

    // @@protoc_insertion_point(class_scope:WISE.Comms.ServerProto.FileUpload.UploadType)
    private static final ca.wise.comms.server.proto.FileUpload.UploadType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.wise.comms.server.proto.FileUpload.UploadType();
    }

    public static ca.wise.comms.server.proto.FileUpload.UploadType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadType>
        PARSER = new com.google.protobuf.AbstractParser<UploadType>() {
      @java.lang.Override
      public UploadType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.wise.comms.server.proto.FileUpload.UploadType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int JOB_FIELD_NUMBER = 1;
  private volatile java.lang.Object job_;
  /**
   * <pre>
   *The name of the job that the file is for.
   *Will be used to find the correct receiver as well as to find the file in the job directory.
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The job.
   */
  @java.lang.Override
  public java.lang.String getJob() {
    java.lang.Object ref = job_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      job_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The name of the job that the file is for.
   *Will be used to find the correct receiver as well as to find the file in the job directory.
   * </pre>
   *
   * <code>string job = 1;</code>
   * @return The bytes for job.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobBytes() {
    java.lang.Object ref = job_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      job_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object filename_;
  /**
   * <pre>
   *The name of the file to upload, including all subfolders within the jobs folder.
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  @java.lang.Override
  public java.lang.String getFilename() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filename_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The name of the file to upload, including all subfolders within the jobs folder.
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    java.lang.Object ref = filename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPLOAD_TYPE_FIELD_NUMBER = 3;
  private java.util.List<ca.wise.comms.server.proto.FileUpload.UploadType> uploadType_;
  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  @java.lang.Override
  public java.util.List<ca.wise.comms.server.proto.FileUpload.UploadType> getUploadTypeList() {
    return uploadType_;
  }
  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder> 
      getUploadTypeOrBuilderList() {
    return uploadType_;
  }
  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  @java.lang.Override
  public int getUploadTypeCount() {
    return uploadType_.size();
  }
  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  @java.lang.Override
  public ca.wise.comms.server.proto.FileUpload.UploadType getUploadType(int index) {
    return uploadType_.get(index);
  }
  /**
   * <pre>
   *An array of methods to use to upload the file.
   * </pre>
   *
   * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
   */
  @java.lang.Override
  public ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder getUploadTypeOrBuilder(
      int index) {
    return uploadType_.get(index);
  }

  public static final int FILETYPE_FIELD_NUMBER = 4;
  private int filetype_;
  /**
   * <pre>
   *The type of file to upload
   * </pre>
   *
   * <code>.WISE.Comms.ServerProto.FileUpload.FileType filetype = 4;</code>
   * @return The enum numeric value on the wire for filetype.
   */
  @java.lang.Override public int getFiletypeValue() {
    return filetype_;
  }
  /**
   * <pre>
   *The type of file to upload
   * </pre>
   *
   * <code>.WISE.Comms.ServerProto.FileUpload.FileType filetype = 4;</code>
   * @return The filetype.
   */
  @java.lang.Override public ca.wise.comms.server.proto.FileUpload.FileType getFiletype() {
    @SuppressWarnings("deprecation")
    ca.wise.comms.server.proto.FileUpload.FileType result = ca.wise.comms.server.proto.FileUpload.FileType.valueOf(filetype_);
    return result == null ? ca.wise.comms.server.proto.FileUpload.FileType.UNRECOGNIZED : result;
  }

  public static final int EXISTS_FIELD_NUMBER = 5;
  private boolean exists_;
  /**
   * <pre>
   *Does the file exist or was it skipped because it would be empty
   * </pre>
   *
   * <code>bool exists = 5;</code>
   * @return The exists.
   */
  @java.lang.Override
  public boolean getExists() {
    return exists_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getJobBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, job_);
    }
    if (!getFilenameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filename_);
    }
    for (int i = 0; i < uploadType_.size(); i++) {
      output.writeMessage(3, uploadType_.get(i));
    }
    if (filetype_ != ca.wise.comms.server.proto.FileUpload.FileType.Unknown.getNumber()) {
      output.writeEnum(4, filetype_);
    }
    if (exists_ != false) {
      output.writeBool(5, exists_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getJobBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, job_);
    }
    if (!getFilenameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filename_);
    }
    for (int i = 0; i < uploadType_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, uploadType_.get(i));
    }
    if (filetype_ != ca.wise.comms.server.proto.FileUpload.FileType.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, filetype_);
    }
    if (exists_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, exists_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.comms.server.proto.FileUpload)) {
      return super.equals(obj);
    }
    ca.wise.comms.server.proto.FileUpload other = (ca.wise.comms.server.proto.FileUpload) obj;

    if (!getJob()
        .equals(other.getJob())) return false;
    if (!getFilename()
        .equals(other.getFilename())) return false;
    if (!getUploadTypeList()
        .equals(other.getUploadTypeList())) return false;
    if (filetype_ != other.filetype_) return false;
    if (getExists()
        != other.getExists()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JOB_FIELD_NUMBER;
    hash = (53 * hash) + getJob().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFilename().hashCode();
    if (getUploadTypeCount() > 0) {
      hash = (37 * hash) + UPLOAD_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getUploadTypeList().hashCode();
    }
    hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
    hash = (53 * hash) + filetype_;
    hash = (37 * hash) + EXISTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getExists());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.comms.server.proto.FileUpload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.comms.server.proto.FileUpload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.FileUpload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.comms.server.proto.FileUpload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.FileUpload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.comms.server.proto.FileUpload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.FileUpload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.comms.server.proto.FileUpload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.FileUpload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.comms.server.proto.FileUpload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.FileUpload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.comms.server.proto.FileUpload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.comms.server.proto.FileUpload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * A wrapper around a file upload request from W.I.S.E.
   * to W.I.S.E. Manager.
   * </pre>
   *
   * Protobuf type {@code WISE.Comms.ServerProto.FileUpload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.Comms.ServerProto.FileUpload)
      ca.wise.comms.server.proto.FileUploadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.comms.server.proto.FileUpload.class, ca.wise.comms.server.proto.FileUpload.Builder.class);
    }

    // Construct using ca.wise.comms.server.proto.FileUpload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUploadTypeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      job_ = "";

      filename_ = "";

      if (uploadTypeBuilder_ == null) {
        uploadType_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        uploadTypeBuilder_.clear();
      }
      filetype_ = 0;

      exists_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_FileUpload_descriptor;
    }

    @java.lang.Override
    public ca.wise.comms.server.proto.FileUpload getDefaultInstanceForType() {
      return ca.wise.comms.server.proto.FileUpload.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.comms.server.proto.FileUpload build() {
      ca.wise.comms.server.proto.FileUpload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.comms.server.proto.FileUpload buildPartial() {
      ca.wise.comms.server.proto.FileUpload result = new ca.wise.comms.server.proto.FileUpload(this);
      int from_bitField0_ = bitField0_;
      result.job_ = job_;
      result.filename_ = filename_;
      if (uploadTypeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          uploadType_ = java.util.Collections.unmodifiableList(uploadType_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.uploadType_ = uploadType_;
      } else {
        result.uploadType_ = uploadTypeBuilder_.build();
      }
      result.filetype_ = filetype_;
      result.exists_ = exists_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.comms.server.proto.FileUpload) {
        return mergeFrom((ca.wise.comms.server.proto.FileUpload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.comms.server.proto.FileUpload other) {
      if (other == ca.wise.comms.server.proto.FileUpload.getDefaultInstance()) return this;
      if (!other.getJob().isEmpty()) {
        job_ = other.job_;
        onChanged();
      }
      if (!other.getFilename().isEmpty()) {
        filename_ = other.filename_;
        onChanged();
      }
      if (uploadTypeBuilder_ == null) {
        if (!other.uploadType_.isEmpty()) {
          if (uploadType_.isEmpty()) {
            uploadType_ = other.uploadType_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUploadTypeIsMutable();
            uploadType_.addAll(other.uploadType_);
          }
          onChanged();
        }
      } else {
        if (!other.uploadType_.isEmpty()) {
          if (uploadTypeBuilder_.isEmpty()) {
            uploadTypeBuilder_.dispose();
            uploadTypeBuilder_ = null;
            uploadType_ = other.uploadType_;
            bitField0_ = (bitField0_ & ~0x00000001);
            uploadTypeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUploadTypeFieldBuilder() : null;
          } else {
            uploadTypeBuilder_.addAllMessages(other.uploadType_);
          }
        }
      }
      if (other.filetype_ != 0) {
        setFiletypeValue(other.getFiletypeValue());
      }
      if (other.getExists() != false) {
        setExists(other.getExists());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.comms.server.proto.FileUpload parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.comms.server.proto.FileUpload) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object job_ = "";
    /**
     * <pre>
     *The name of the job that the file is for.
     *Will be used to find the correct receiver as well as to find the file in the job directory.
     * </pre>
     *
     * <code>string job = 1;</code>
     * @return The job.
     */
    public java.lang.String getJob() {
      java.lang.Object ref = job_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        job_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The name of the job that the file is for.
     *Will be used to find the correct receiver as well as to find the file in the job directory.
     * </pre>
     *
     * <code>string job = 1;</code>
     * @return The bytes for job.
     */
    public com.google.protobuf.ByteString
        getJobBytes() {
      java.lang.Object ref = job_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        job_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The name of the job that the file is for.
     *Will be used to find the correct receiver as well as to find the file in the job directory.
     * </pre>
     *
     * <code>string job = 1;</code>
     * @param value The job to set.
     * @return This builder for chaining.
     */
    public Builder setJob(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      job_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The name of the job that the file is for.
     *Will be used to find the correct receiver as well as to find the file in the job directory.
     * </pre>
     *
     * <code>string job = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJob() {
      
      job_ = getDefaultInstance().getJob();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The name of the job that the file is for.
     *Will be used to find the correct receiver as well as to find the file in the job directory.
     * </pre>
     *
     * <code>string job = 1;</code>
     * @param value The bytes for job to set.
     * @return This builder for chaining.
     */
    public Builder setJobBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      job_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object filename_ = "";
    /**
     * <pre>
     *The name of the file to upload, including all subfolders within the jobs folder.
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @return The filename.
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The name of the file to upload, including all subfolders within the jobs folder.
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @return The bytes for filename.
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The name of the file to upload, including all subfolders within the jobs folder.
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filename_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The name of the file to upload, including all subfolders within the jobs folder.
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      
      filename_ = getDefaultInstance().getFilename();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The name of the file to upload, including all subfolders within the jobs folder.
     * </pre>
     *
     * <code>string filename = 2;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filename_ = value;
      onChanged();
      return this;
    }

    private java.util.List<ca.wise.comms.server.proto.FileUpload.UploadType> uploadType_ =
      java.util.Collections.emptyList();
    private void ensureUploadTypeIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        uploadType_ = new java.util.ArrayList<ca.wise.comms.server.proto.FileUpload.UploadType>(uploadType_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.comms.server.proto.FileUpload.UploadType, ca.wise.comms.server.proto.FileUpload.UploadType.Builder, ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder> uploadTypeBuilder_;

    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public java.util.List<ca.wise.comms.server.proto.FileUpload.UploadType> getUploadTypeList() {
      if (uploadTypeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(uploadType_);
      } else {
        return uploadTypeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public int getUploadTypeCount() {
      if (uploadTypeBuilder_ == null) {
        return uploadType_.size();
      } else {
        return uploadTypeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public ca.wise.comms.server.proto.FileUpload.UploadType getUploadType(int index) {
      if (uploadTypeBuilder_ == null) {
        return uploadType_.get(index);
      } else {
        return uploadTypeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public Builder setUploadType(
        int index, ca.wise.comms.server.proto.FileUpload.UploadType value) {
      if (uploadTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUploadTypeIsMutable();
        uploadType_.set(index, value);
        onChanged();
      } else {
        uploadTypeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public Builder setUploadType(
        int index, ca.wise.comms.server.proto.FileUpload.UploadType.Builder builderForValue) {
      if (uploadTypeBuilder_ == null) {
        ensureUploadTypeIsMutable();
        uploadType_.set(index, builderForValue.build());
        onChanged();
      } else {
        uploadTypeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public Builder addUploadType(ca.wise.comms.server.proto.FileUpload.UploadType value) {
      if (uploadTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUploadTypeIsMutable();
        uploadType_.add(value);
        onChanged();
      } else {
        uploadTypeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public Builder addUploadType(
        int index, ca.wise.comms.server.proto.FileUpload.UploadType value) {
      if (uploadTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUploadTypeIsMutable();
        uploadType_.add(index, value);
        onChanged();
      } else {
        uploadTypeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public Builder addUploadType(
        ca.wise.comms.server.proto.FileUpload.UploadType.Builder builderForValue) {
      if (uploadTypeBuilder_ == null) {
        ensureUploadTypeIsMutable();
        uploadType_.add(builderForValue.build());
        onChanged();
      } else {
        uploadTypeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public Builder addUploadType(
        int index, ca.wise.comms.server.proto.FileUpload.UploadType.Builder builderForValue) {
      if (uploadTypeBuilder_ == null) {
        ensureUploadTypeIsMutable();
        uploadType_.add(index, builderForValue.build());
        onChanged();
      } else {
        uploadTypeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public Builder addAllUploadType(
        java.lang.Iterable<? extends ca.wise.comms.server.proto.FileUpload.UploadType> values) {
      if (uploadTypeBuilder_ == null) {
        ensureUploadTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, uploadType_);
        onChanged();
      } else {
        uploadTypeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public Builder clearUploadType() {
      if (uploadTypeBuilder_ == null) {
        uploadType_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        uploadTypeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public Builder removeUploadType(int index) {
      if (uploadTypeBuilder_ == null) {
        ensureUploadTypeIsMutable();
        uploadType_.remove(index);
        onChanged();
      } else {
        uploadTypeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public ca.wise.comms.server.proto.FileUpload.UploadType.Builder getUploadTypeBuilder(
        int index) {
      return getUploadTypeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder getUploadTypeOrBuilder(
        int index) {
      if (uploadTypeBuilder_ == null) {
        return uploadType_.get(index);  } else {
        return uploadTypeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public java.util.List<? extends ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder> 
         getUploadTypeOrBuilderList() {
      if (uploadTypeBuilder_ != null) {
        return uploadTypeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(uploadType_);
      }
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public ca.wise.comms.server.proto.FileUpload.UploadType.Builder addUploadTypeBuilder() {
      return getUploadTypeFieldBuilder().addBuilder(
          ca.wise.comms.server.proto.FileUpload.UploadType.getDefaultInstance());
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public ca.wise.comms.server.proto.FileUpload.UploadType.Builder addUploadTypeBuilder(
        int index) {
      return getUploadTypeFieldBuilder().addBuilder(
          index, ca.wise.comms.server.proto.FileUpload.UploadType.getDefaultInstance());
    }
    /**
     * <pre>
     *An array of methods to use to upload the file.
     * </pre>
     *
     * <code>repeated .WISE.Comms.ServerProto.FileUpload.UploadType upload_type = 3;</code>
     */
    public java.util.List<ca.wise.comms.server.proto.FileUpload.UploadType.Builder> 
         getUploadTypeBuilderList() {
      return getUploadTypeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ca.wise.comms.server.proto.FileUpload.UploadType, ca.wise.comms.server.proto.FileUpload.UploadType.Builder, ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder> 
        getUploadTypeFieldBuilder() {
      if (uploadTypeBuilder_ == null) {
        uploadTypeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ca.wise.comms.server.proto.FileUpload.UploadType, ca.wise.comms.server.proto.FileUpload.UploadType.Builder, ca.wise.comms.server.proto.FileUpload.UploadTypeOrBuilder>(
                uploadType_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        uploadType_ = null;
      }
      return uploadTypeBuilder_;
    }

    private int filetype_ = 0;
    /**
     * <pre>
     *The type of file to upload
     * </pre>
     *
     * <code>.WISE.Comms.ServerProto.FileUpload.FileType filetype = 4;</code>
     * @return The enum numeric value on the wire for filetype.
     */
    @java.lang.Override public int getFiletypeValue() {
      return filetype_;
    }
    /**
     * <pre>
     *The type of file to upload
     * </pre>
     *
     * <code>.WISE.Comms.ServerProto.FileUpload.FileType filetype = 4;</code>
     * @param value The enum numeric value on the wire for filetype to set.
     * @return This builder for chaining.
     */
    public Builder setFiletypeValue(int value) {
      
      filetype_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The type of file to upload
     * </pre>
     *
     * <code>.WISE.Comms.ServerProto.FileUpload.FileType filetype = 4;</code>
     * @return The filetype.
     */
    @java.lang.Override
    public ca.wise.comms.server.proto.FileUpload.FileType getFiletype() {
      @SuppressWarnings("deprecation")
      ca.wise.comms.server.proto.FileUpload.FileType result = ca.wise.comms.server.proto.FileUpload.FileType.valueOf(filetype_);
      return result == null ? ca.wise.comms.server.proto.FileUpload.FileType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *The type of file to upload
     * </pre>
     *
     * <code>.WISE.Comms.ServerProto.FileUpload.FileType filetype = 4;</code>
     * @param value The filetype to set.
     * @return This builder for chaining.
     */
    public Builder setFiletype(ca.wise.comms.server.proto.FileUpload.FileType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      filetype_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The type of file to upload
     * </pre>
     *
     * <code>.WISE.Comms.ServerProto.FileUpload.FileType filetype = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFiletype() {
      
      filetype_ = 0;
      onChanged();
      return this;
    }

    private boolean exists_ ;
    /**
     * <pre>
     *Does the file exist or was it skipped because it would be empty
     * </pre>
     *
     * <code>bool exists = 5;</code>
     * @return The exists.
     */
    @java.lang.Override
    public boolean getExists() {
      return exists_;
    }
    /**
     * <pre>
     *Does the file exist or was it skipped because it would be empty
     * </pre>
     *
     * <code>bool exists = 5;</code>
     * @param value The exists to set.
     * @return This builder for chaining.
     */
    public Builder setExists(boolean value) {
      
      exists_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Does the file exist or was it skipped because it would be empty
     * </pre>
     *
     * <code>bool exists = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExists() {
      
      exists_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.Comms.ServerProto.FileUpload)
  }

  // @@protoc_insertion_point(class_scope:WISE.Comms.ServerProto.FileUpload)
  private static final ca.wise.comms.server.proto.FileUpload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.comms.server.proto.FileUpload();
  }

  public static ca.wise.comms.server.proto.FileUpload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileUpload>
      PARSER = new com.google.protobuf.AbstractParser<FileUpload>() {
    @java.lang.Override
    public FileUpload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileUpload(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileUpload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileUpload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.comms.server.proto.FileUpload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

