// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.server.proto;

public final class FileUploadOuterClass {
  private FileUploadOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ServerProto_FileUpload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ServerProto_FileUpload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ServerProto_MQTTUpload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ServerProto_MQTTUpload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ServerProto_GeoserverUpload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ServerProto_GeoserverUpload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021file_upload.proto\022\026WISE.Comms.ServerPr" +
      "oto\032\036google/protobuf/wrappers.proto\"\203\003\n\n" +
      "FileUpload\022\013\n\003job\030\001 \001(\t\022\020\n\010filename\030\002 \001(" +
      "\t\022B\n\013upload_type\030\003 \003(\0132-.WISE.Comms.Serv" +
      "erProto.FileUpload.UploadType\022=\n\010filetyp" +
      "e\030\004 \001(\0162+.WISE.Comms.ServerProto.FileUpl" +
      "oad.FileType\022\016\n\006exists\030\005 \001(\010\032\206\001\n\nUploadT" +
      "ype\0222\n\004mqtt\030\001 \001(\0132\".WISE.Comms.ServerPro" +
      "to.MQTTUploadH\000\022<\n\tgeoserver\030\002 \001(\0132\'.WIS" +
      "E.Comms.ServerProto.GeoserverUploadH\000B\006\n" +
      "\004type\":\n\010FileType\022\013\n\007Unknown\020\000\022\013\n\007Summar" +
      "y\020\001\022\n\n\006Vector\020\002\022\010\n\004Grid\020\003\"0\n\nMQTTUpload\022" +
      "\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\342\001\n\017" +
      "GeoserverUpload\022\020\n\010username\030\001 \001(\t\022\020\n\010pas" +
      "sword\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\022\021\n\tworkspace\030\004 " +
      "\001(\t\022\020\n\010coverage\030\005 \001(\t\022\013\n\003srs\030\006 \001(\t\0225\n\017ve" +
      "ctor_coverage\030\007 \001(\0132\034.google.protobuf.St" +
      "ringValue\0225\n\017raster_coverage\030\010 \001(\0132\034.goo" +
      "gle.protobuf.StringValueB7\n\032ca.wise.comm" +
      "s.server.protoP\001\252\002\026WISE.Comms.ServerProt" +
      "ob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_WISE_Comms_ServerProto_FileUpload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_Comms_ServerProto_FileUpload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ServerProto_FileUpload_descriptor,
        new java.lang.String[] { "Job", "Filename", "UploadType", "Filetype", "Exists", });
    internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_descriptor =
      internal_static_WISE_Comms_ServerProto_FileUpload_descriptor.getNestedTypes().get(0);
    internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ServerProto_FileUpload_UploadType_descriptor,
        new java.lang.String[] { "Mqtt", "Geoserver", "Type", });
    internal_static_WISE_Comms_ServerProto_MQTTUpload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WISE_Comms_ServerProto_MQTTUpload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ServerProto_MQTTUpload_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_WISE_Comms_ServerProto_GeoserverUpload_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WISE_Comms_ServerProto_GeoserverUpload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ServerProto_GeoserverUpload_descriptor,
        new java.lang.String[] { "Username", "Password", "Url", "Workspace", "Coverage", "Srs", "VectorCoverage", "RasterCoverage", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
