// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.server.proto;

/**
 * <pre>
 **
 * A message that will be passed from W.I.S.E. to Manager to
 * initialize a file upload to a GeoServer instance.
 * </pre>
 *
 * Protobuf type {@code WISE.Comms.ServerProto.GeoserverUpload}
 */
public final class GeoserverUpload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WISE.Comms.ServerProto.GeoserverUpload)
    GeoserverUploadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GeoserverUpload.newBuilder() to construct.
  private GeoserverUpload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GeoserverUpload() {
    username_ = "";
    password_ = "";
    url_ = "";
    workspace_ = "";
    coverage_ = "";
    srs_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GeoserverUpload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GeoserverUpload(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            workspace_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            coverage_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            srs_ = s;
            break;
          }
          case 58: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (vectorCoverage_ != null) {
              subBuilder = vectorCoverage_.toBuilder();
            }
            vectorCoverage_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vectorCoverage_);
              vectorCoverage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (rasterCoverage_ != null) {
              subBuilder = rasterCoverage_.toBuilder();
            }
            rasterCoverage_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rasterCoverage_);
              rasterCoverage_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_GeoserverUpload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_GeoserverUpload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ca.wise.comms.server.proto.GeoserverUpload.class, ca.wise.comms.server.proto.GeoserverUpload.Builder.class);
  }

  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object username_;
  /**
   * <pre>
   *A username to authenticate on the geoserver with.
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *A username to authenticate on the geoserver with.
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 2;
  private volatile java.lang.Object password_;
  /**
   * <pre>
   *A password to authenticate on the geoserver with.
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *A password to authenticate on the geoserver with.
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URL_FIELD_NUMBER = 3;
  private volatile java.lang.Object url_;
  /**
   * <pre>
   *The base URL of the geoserver instance. The address of the rest API should be {url}/rest.
   * </pre>
   *
   * <code>string url = 3;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The base URL of the geoserver instance. The address of the rest API should be {url}/rest.
   * </pre>
   *
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKSPACE_FIELD_NUMBER = 4;
  private volatile java.lang.Object workspace_;
  /**
   * <pre>
   *The workspace to load the file into.
   * </pre>
   *
   * <code>string workspace = 4;</code>
   * @return The workspace.
   */
  @java.lang.Override
  public java.lang.String getWorkspace() {
    java.lang.Object ref = workspace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workspace_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The workspace to load the file into.
   * </pre>
   *
   * <code>string workspace = 4;</code>
   * @return The bytes for workspace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorkspaceBytes() {
    java.lang.Object ref = workspace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workspace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COVERAGE_FIELD_NUMBER = 5;
  private volatile java.lang.Object coverage_;
  /**
   * <pre>
   *The name of the coverage store to create or update.
   * </pre>
   *
   * <code>string coverage = 5;</code>
   * @return The coverage.
   */
  @java.lang.Override
  public java.lang.String getCoverage() {
    java.lang.Object ref = coverage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      coverage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The name of the coverage store to create or update.
   * </pre>
   *
   * <code>string coverage = 5;</code>
   * @return The bytes for coverage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCoverageBytes() {
    java.lang.Object ref = coverage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      coverage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRS_FIELD_NUMBER = 6;
  private volatile java.lang.Object srs_;
  /**
   * <pre>
   *The declared spatial reference system for the added coverage.
   * </pre>
   *
   * <code>string srs = 6;</code>
   * @return The srs.
   */
  @java.lang.Override
  public java.lang.String getSrs() {
    java.lang.Object ref = srs_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      srs_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *The declared spatial reference system for the added coverage.
   * </pre>
   *
   * <code>string srs = 6;</code>
   * @return The bytes for srs.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSrsBytes() {
    java.lang.Object ref = srs_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      srs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VECTOR_COVERAGE_FIELD_NUMBER = 7;
  private com.google.protobuf.StringValue vectorCoverage_;
  /**
   * <pre>
   *An override for the coverage store if a vector file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
   * @return Whether the vectorCoverage field is set.
   */
  @java.lang.Override
  public boolean hasVectorCoverage() {
    return vectorCoverage_ != null;
  }
  /**
   * <pre>
   *An override for the coverage store if a vector file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
   * @return The vectorCoverage.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getVectorCoverage() {
    return vectorCoverage_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : vectorCoverage_;
  }
  /**
   * <pre>
   *An override for the coverage store if a vector file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getVectorCoverageOrBuilder() {
    return getVectorCoverage();
  }

  public static final int RASTER_COVERAGE_FIELD_NUMBER = 8;
  private com.google.protobuf.StringValue rasterCoverage_;
  /**
   * <pre>
   *An override for the coverage store if a raster file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
   * @return Whether the rasterCoverage field is set.
   */
  @java.lang.Override
  public boolean hasRasterCoverage() {
    return rasterCoverage_ != null;
  }
  /**
   * <pre>
   *An override for the coverage store if a raster file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
   * @return The rasterCoverage.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getRasterCoverage() {
    return rasterCoverage_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : rasterCoverage_;
  }
  /**
   * <pre>
   *An override for the coverage store if a raster file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getRasterCoverageOrBuilder() {
    return getRasterCoverage();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
    }
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, url_);
    }
    if (!getWorkspaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, workspace_);
    }
    if (!getCoverageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, coverage_);
    }
    if (!getSrsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, srs_);
    }
    if (vectorCoverage_ != null) {
      output.writeMessage(7, getVectorCoverage());
    }
    if (rasterCoverage_ != null) {
      output.writeMessage(8, getRasterCoverage());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
    }
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, url_);
    }
    if (!getWorkspaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, workspace_);
    }
    if (!getCoverageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, coverage_);
    }
    if (!getSrsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, srs_);
    }
    if (vectorCoverage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getVectorCoverage());
    }
    if (rasterCoverage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getRasterCoverage());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ca.wise.comms.server.proto.GeoserverUpload)) {
      return super.equals(obj);
    }
    ca.wise.comms.server.proto.GeoserverUpload other = (ca.wise.comms.server.proto.GeoserverUpload) obj;

    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (!getWorkspace()
        .equals(other.getWorkspace())) return false;
    if (!getCoverage()
        .equals(other.getCoverage())) return false;
    if (!getSrs()
        .equals(other.getSrs())) return false;
    if (hasVectorCoverage() != other.hasVectorCoverage()) return false;
    if (hasVectorCoverage()) {
      if (!getVectorCoverage()
          .equals(other.getVectorCoverage())) return false;
    }
    if (hasRasterCoverage() != other.hasRasterCoverage()) return false;
    if (hasRasterCoverage()) {
      if (!getRasterCoverage()
          .equals(other.getRasterCoverage())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (37 * hash) + WORKSPACE_FIELD_NUMBER;
    hash = (53 * hash) + getWorkspace().hashCode();
    hash = (37 * hash) + COVERAGE_FIELD_NUMBER;
    hash = (53 * hash) + getCoverage().hashCode();
    hash = (37 * hash) + SRS_FIELD_NUMBER;
    hash = (53 * hash) + getSrs().hashCode();
    if (hasVectorCoverage()) {
      hash = (37 * hash) + VECTOR_COVERAGE_FIELD_NUMBER;
      hash = (53 * hash) + getVectorCoverage().hashCode();
    }
    if (hasRasterCoverage()) {
      hash = (37 * hash) + RASTER_COVERAGE_FIELD_NUMBER;
      hash = (53 * hash) + getRasterCoverage().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ca.wise.comms.server.proto.GeoserverUpload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ca.wise.comms.server.proto.GeoserverUpload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * A message that will be passed from W.I.S.E. to Manager to
   * initialize a file upload to a GeoServer instance.
   * </pre>
   *
   * Protobuf type {@code WISE.Comms.ServerProto.GeoserverUpload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WISE.Comms.ServerProto.GeoserverUpload)
      ca.wise.comms.server.proto.GeoserverUploadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_GeoserverUpload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_GeoserverUpload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.wise.comms.server.proto.GeoserverUpload.class, ca.wise.comms.server.proto.GeoserverUpload.Builder.class);
    }

    // Construct using ca.wise.comms.server.proto.GeoserverUpload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      username_ = "";

      password_ = "";

      url_ = "";

      workspace_ = "";

      coverage_ = "";

      srs_ = "";

      if (vectorCoverageBuilder_ == null) {
        vectorCoverage_ = null;
      } else {
        vectorCoverage_ = null;
        vectorCoverageBuilder_ = null;
      }
      if (rasterCoverageBuilder_ == null) {
        rasterCoverage_ = null;
      } else {
        rasterCoverage_ = null;
        rasterCoverageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ca.wise.comms.server.proto.FileUploadOuterClass.internal_static_WISE_Comms_ServerProto_GeoserverUpload_descriptor;
    }

    @java.lang.Override
    public ca.wise.comms.server.proto.GeoserverUpload getDefaultInstanceForType() {
      return ca.wise.comms.server.proto.GeoserverUpload.getDefaultInstance();
    }

    @java.lang.Override
    public ca.wise.comms.server.proto.GeoserverUpload build() {
      ca.wise.comms.server.proto.GeoserverUpload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ca.wise.comms.server.proto.GeoserverUpload buildPartial() {
      ca.wise.comms.server.proto.GeoserverUpload result = new ca.wise.comms.server.proto.GeoserverUpload(this);
      result.username_ = username_;
      result.password_ = password_;
      result.url_ = url_;
      result.workspace_ = workspace_;
      result.coverage_ = coverage_;
      result.srs_ = srs_;
      if (vectorCoverageBuilder_ == null) {
        result.vectorCoverage_ = vectorCoverage_;
      } else {
        result.vectorCoverage_ = vectorCoverageBuilder_.build();
      }
      if (rasterCoverageBuilder_ == null) {
        result.rasterCoverage_ = rasterCoverage_;
      } else {
        result.rasterCoverage_ = rasterCoverageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ca.wise.comms.server.proto.GeoserverUpload) {
        return mergeFrom((ca.wise.comms.server.proto.GeoserverUpload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ca.wise.comms.server.proto.GeoserverUpload other) {
      if (other == ca.wise.comms.server.proto.GeoserverUpload.getDefaultInstance()) return this;
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      if (!other.getWorkspace().isEmpty()) {
        workspace_ = other.workspace_;
        onChanged();
      }
      if (!other.getCoverage().isEmpty()) {
        coverage_ = other.coverage_;
        onChanged();
      }
      if (!other.getSrs().isEmpty()) {
        srs_ = other.srs_;
        onChanged();
      }
      if (other.hasVectorCoverage()) {
        mergeVectorCoverage(other.getVectorCoverage());
      }
      if (other.hasRasterCoverage()) {
        mergeRasterCoverage(other.getRasterCoverage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ca.wise.comms.server.proto.GeoserverUpload parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ca.wise.comms.server.proto.GeoserverUpload) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <pre>
     *A username to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *A username to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *A username to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A username to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A username to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <pre>
     *A password to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string password = 2;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *A password to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *A password to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string password = 2;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A password to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string password = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A password to authenticate on the geoserver with.
     * </pre>
     *
     * <code>string password = 2;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <pre>
     *The base URL of the geoserver instance. The address of the rest API should be {url}/rest.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The base URL of the geoserver instance. The address of the rest API should be {url}/rest.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The base URL of the geoserver instance. The address of the rest API should be {url}/rest.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The base URL of the geoserver instance. The address of the rest API should be {url}/rest.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The base URL of the geoserver instance. The address of the rest API should be {url}/rest.
     * </pre>
     *
     * <code>string url = 3;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object workspace_ = "";
    /**
     * <pre>
     *The workspace to load the file into.
     * </pre>
     *
     * <code>string workspace = 4;</code>
     * @return The workspace.
     */
    public java.lang.String getWorkspace() {
      java.lang.Object ref = workspace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workspace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The workspace to load the file into.
     * </pre>
     *
     * <code>string workspace = 4;</code>
     * @return The bytes for workspace.
     */
    public com.google.protobuf.ByteString
        getWorkspaceBytes() {
      java.lang.Object ref = workspace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workspace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The workspace to load the file into.
     * </pre>
     *
     * <code>string workspace = 4;</code>
     * @param value The workspace to set.
     * @return This builder for chaining.
     */
    public Builder setWorkspace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workspace_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The workspace to load the file into.
     * </pre>
     *
     * <code>string workspace = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkspace() {
      
      workspace_ = getDefaultInstance().getWorkspace();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The workspace to load the file into.
     * </pre>
     *
     * <code>string workspace = 4;</code>
     * @param value The bytes for workspace to set.
     * @return This builder for chaining.
     */
    public Builder setWorkspaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workspace_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object coverage_ = "";
    /**
     * <pre>
     *The name of the coverage store to create or update.
     * </pre>
     *
     * <code>string coverage = 5;</code>
     * @return The coverage.
     */
    public java.lang.String getCoverage() {
      java.lang.Object ref = coverage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coverage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The name of the coverage store to create or update.
     * </pre>
     *
     * <code>string coverage = 5;</code>
     * @return The bytes for coverage.
     */
    public com.google.protobuf.ByteString
        getCoverageBytes() {
      java.lang.Object ref = coverage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coverage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The name of the coverage store to create or update.
     * </pre>
     *
     * <code>string coverage = 5;</code>
     * @param value The coverage to set.
     * @return This builder for chaining.
     */
    public Builder setCoverage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      coverage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The name of the coverage store to create or update.
     * </pre>
     *
     * <code>string coverage = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoverage() {
      
      coverage_ = getDefaultInstance().getCoverage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The name of the coverage store to create or update.
     * </pre>
     *
     * <code>string coverage = 5;</code>
     * @param value The bytes for coverage to set.
     * @return This builder for chaining.
     */
    public Builder setCoverageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      coverage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object srs_ = "";
    /**
     * <pre>
     *The declared spatial reference system for the added coverage.
     * </pre>
     *
     * <code>string srs = 6;</code>
     * @return The srs.
     */
    public java.lang.String getSrs() {
      java.lang.Object ref = srs_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srs_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *The declared spatial reference system for the added coverage.
     * </pre>
     *
     * <code>string srs = 6;</code>
     * @return The bytes for srs.
     */
    public com.google.protobuf.ByteString
        getSrsBytes() {
      java.lang.Object ref = srs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *The declared spatial reference system for the added coverage.
     * </pre>
     *
     * <code>string srs = 6;</code>
     * @param value The srs to set.
     * @return This builder for chaining.
     */
    public Builder setSrs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The declared spatial reference system for the added coverage.
     * </pre>
     *
     * <code>string srs = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrs() {
      
      srs_ = getDefaultInstance().getSrs();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *The declared spatial reference system for the added coverage.
     * </pre>
     *
     * <code>string srs = 6;</code>
     * @param value The bytes for srs to set.
     * @return This builder for chaining.
     */
    public Builder setSrsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srs_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.StringValue vectorCoverage_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> vectorCoverageBuilder_;
    /**
     * <pre>
     *An override for the coverage store if a vector file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
     * @return Whether the vectorCoverage field is set.
     */
    public boolean hasVectorCoverage() {
      return vectorCoverageBuilder_ != null || vectorCoverage_ != null;
    }
    /**
     * <pre>
     *An override for the coverage store if a vector file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
     * @return The vectorCoverage.
     */
    public com.google.protobuf.StringValue getVectorCoverage() {
      if (vectorCoverageBuilder_ == null) {
        return vectorCoverage_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : vectorCoverage_;
      } else {
        return vectorCoverageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *An override for the coverage store if a vector file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
     */
    public Builder setVectorCoverage(com.google.protobuf.StringValue value) {
      if (vectorCoverageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vectorCoverage_ = value;
        onChanged();
      } else {
        vectorCoverageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *An override for the coverage store if a vector file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
     */
    public Builder setVectorCoverage(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (vectorCoverageBuilder_ == null) {
        vectorCoverage_ = builderForValue.build();
        onChanged();
      } else {
        vectorCoverageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *An override for the coverage store if a vector file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
     */
    public Builder mergeVectorCoverage(com.google.protobuf.StringValue value) {
      if (vectorCoverageBuilder_ == null) {
        if (vectorCoverage_ != null) {
          vectorCoverage_ =
            com.google.protobuf.StringValue.newBuilder(vectorCoverage_).mergeFrom(value).buildPartial();
        } else {
          vectorCoverage_ = value;
        }
        onChanged();
      } else {
        vectorCoverageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *An override for the coverage store if a vector file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
     */
    public Builder clearVectorCoverage() {
      if (vectorCoverageBuilder_ == null) {
        vectorCoverage_ = null;
        onChanged();
      } else {
        vectorCoverage_ = null;
        vectorCoverageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *An override for the coverage store if a vector file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
     */
    public com.google.protobuf.StringValue.Builder getVectorCoverageBuilder() {
      
      onChanged();
      return getVectorCoverageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *An override for the coverage store if a vector file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getVectorCoverageOrBuilder() {
      if (vectorCoverageBuilder_ != null) {
        return vectorCoverageBuilder_.getMessageOrBuilder();
      } else {
        return vectorCoverage_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : vectorCoverage_;
      }
    }
    /**
     * <pre>
     *An override for the coverage store if a vector file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getVectorCoverageFieldBuilder() {
      if (vectorCoverageBuilder_ == null) {
        vectorCoverageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getVectorCoverage(),
                getParentForChildren(),
                isClean());
        vectorCoverage_ = null;
      }
      return vectorCoverageBuilder_;
    }

    private com.google.protobuf.StringValue rasterCoverage_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> rasterCoverageBuilder_;
    /**
     * <pre>
     *An override for the coverage store if a raster file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
     * @return Whether the rasterCoverage field is set.
     */
    public boolean hasRasterCoverage() {
      return rasterCoverageBuilder_ != null || rasterCoverage_ != null;
    }
    /**
     * <pre>
     *An override for the coverage store if a raster file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
     * @return The rasterCoverage.
     */
    public com.google.protobuf.StringValue getRasterCoverage() {
      if (rasterCoverageBuilder_ == null) {
        return rasterCoverage_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : rasterCoverage_;
      } else {
        return rasterCoverageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *An override for the coverage store if a raster file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
     */
    public Builder setRasterCoverage(com.google.protobuf.StringValue value) {
      if (rasterCoverageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rasterCoverage_ = value;
        onChanged();
      } else {
        rasterCoverageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *An override for the coverage store if a raster file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
     */
    public Builder setRasterCoverage(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (rasterCoverageBuilder_ == null) {
        rasterCoverage_ = builderForValue.build();
        onChanged();
      } else {
        rasterCoverageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *An override for the coverage store if a raster file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
     */
    public Builder mergeRasterCoverage(com.google.protobuf.StringValue value) {
      if (rasterCoverageBuilder_ == null) {
        if (rasterCoverage_ != null) {
          rasterCoverage_ =
            com.google.protobuf.StringValue.newBuilder(rasterCoverage_).mergeFrom(value).buildPartial();
        } else {
          rasterCoverage_ = value;
        }
        onChanged();
      } else {
        rasterCoverageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *An override for the coverage store if a raster file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
     */
    public Builder clearRasterCoverage() {
      if (rasterCoverageBuilder_ == null) {
        rasterCoverage_ = null;
        onChanged();
      } else {
        rasterCoverage_ = null;
        rasterCoverageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *An override for the coverage store if a raster file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
     */
    public com.google.protobuf.StringValue.Builder getRasterCoverageBuilder() {
      
      onChanged();
      return getRasterCoverageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *An override for the coverage store if a raster file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getRasterCoverageOrBuilder() {
      if (rasterCoverageBuilder_ != null) {
        return rasterCoverageBuilder_.getMessageOrBuilder();
      } else {
        return rasterCoverage_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : rasterCoverage_;
      }
    }
    /**
     * <pre>
     *An override for the coverage store if a raster file is being uploaded.
     * </pre>
     *
     * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getRasterCoverageFieldBuilder() {
      if (rasterCoverageBuilder_ == null) {
        rasterCoverageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getRasterCoverage(),
                getParentForChildren(),
                isClean());
        rasterCoverage_ = null;
      }
      return rasterCoverageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WISE.Comms.ServerProto.GeoserverUpload)
  }

  // @@protoc_insertion_point(class_scope:WISE.Comms.ServerProto.GeoserverUpload)
  private static final ca.wise.comms.server.proto.GeoserverUpload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ca.wise.comms.server.proto.GeoserverUpload();
  }

  public static ca.wise.comms.server.proto.GeoserverUpload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GeoserverUpload>
      PARSER = new com.google.protobuf.AbstractParser<GeoserverUpload>() {
    @java.lang.Override
    public GeoserverUpload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GeoserverUpload(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GeoserverUpload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GeoserverUpload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ca.wise.comms.server.proto.GeoserverUpload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

