// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.server.proto;

public interface GeoserverUploadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.Comms.ServerProto.GeoserverUpload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *A username to authenticate on the geoserver with.
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   *A username to authenticate on the geoserver with.
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   *A password to authenticate on the geoserver with.
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <pre>
   *A password to authenticate on the geoserver with.
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <pre>
   *The base URL of the geoserver instance. The address of the rest API should be {url}/rest.
   * </pre>
   *
   * <code>string url = 3;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   *The base URL of the geoserver instance. The address of the rest API should be {url}/rest.
   * </pre>
   *
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   *The workspace to load the file into.
   * </pre>
   *
   * <code>string workspace = 4;</code>
   * @return The workspace.
   */
  java.lang.String getWorkspace();
  /**
   * <pre>
   *The workspace to load the file into.
   * </pre>
   *
   * <code>string workspace = 4;</code>
   * @return The bytes for workspace.
   */
  com.google.protobuf.ByteString
      getWorkspaceBytes();

  /**
   * <pre>
   *The name of the coverage store to create or update.
   * </pre>
   *
   * <code>string coverage = 5;</code>
   * @return The coverage.
   */
  java.lang.String getCoverage();
  /**
   * <pre>
   *The name of the coverage store to create or update.
   * </pre>
   *
   * <code>string coverage = 5;</code>
   * @return The bytes for coverage.
   */
  com.google.protobuf.ByteString
      getCoverageBytes();

  /**
   * <pre>
   *The declared spatial reference system for the added coverage.
   * </pre>
   *
   * <code>string srs = 6;</code>
   * @return The srs.
   */
  java.lang.String getSrs();
  /**
   * <pre>
   *The declared spatial reference system for the added coverage.
   * </pre>
   *
   * <code>string srs = 6;</code>
   * @return The bytes for srs.
   */
  com.google.protobuf.ByteString
      getSrsBytes();

  /**
   * <pre>
   *An override for the coverage store if a vector file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
   * @return Whether the vectorCoverage field is set.
   */
  boolean hasVectorCoverage();
  /**
   * <pre>
   *An override for the coverage store if a vector file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
   * @return The vectorCoverage.
   */
  com.google.protobuf.StringValue getVectorCoverage();
  /**
   * <pre>
   *An override for the coverage store if a vector file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue vector_coverage = 7;</code>
   */
  com.google.protobuf.StringValueOrBuilder getVectorCoverageOrBuilder();

  /**
   * <pre>
   *An override for the coverage store if a raster file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
   * @return Whether the rasterCoverage field is set.
   */
  boolean hasRasterCoverage();
  /**
   * <pre>
   *An override for the coverage store if a raster file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
   * @return The rasterCoverage.
   */
  com.google.protobuf.StringValue getRasterCoverage();
  /**
   * <pre>
   *An override for the coverage store if a raster file is being uploaded.
   * </pre>
   *
   * <code>.google.protobuf.StringValue raster_coverage = 8;</code>
   */
  com.google.protobuf.StringValueOrBuilder getRasterCoverageOrBuilder();
}
