// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_upload.proto

package ca.wise.comms.server.proto;

public interface MQTTUploadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WISE.Comms.ServerProto.MQTTUpload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *An optional username to use to authenticate with the MQTT broker.
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   *An optional username to use to authenticate with the MQTT broker.
   * </pre>
   *
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   *An optional password to use to authenticate with the MQTT broker.
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <pre>
   *An optional password to use to authenticate with the MQTT broker.
   * </pre>
   *
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
