// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validation_report.proto

package ca.wise.comms.server.proto;

public final class ValidationReportOuterClass {
  private ValidationReportOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ValidationProto_ValidationReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ValidationProto_ValidationReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_ErrorObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_ErrorObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027validation_report.proto\022\032WISE.Comms.Va" +
      "lidationProto\032\036google/protobuf/wrappers." +
      "proto\"\335\005\n\020ValidationReport\022\017\n\007success\030\001 " +
      "\001(\010\022\r\n\005valid\030\002 \001(\010\0223\n\rload_warnings\030\003 \001(" +
      "\0132\034.google.protobuf.StringValue\022T\n\017valid" +
      "ation_tree\030\004 \001(\0132;.WISE.Comms.Validation" +
      "Proto.ValidationReport.ValidationNode\032\235\004" +
      "\n\016ValidationNode\022[\n\013error_level\030\001 \001(\0162F." +
      "WISE.Comms.ValidationProto.ValidationRep" +
      "ort.ValidationNode.ErrorLevel\022\025\n\rprotobu" +
      "f_name\030\002 \001(\t\022]\n\014error_values\030\003 \003(\0132G.WIS" +
      "E.Comms.ValidationProto.ValidationReport" +
      ".ValidationNode.ErrorObject\022.\n\010error_id\030" +
      "\004 \001(\0132\034.google.protobuf.StringValue\022M\n\010c" +
      "hildren\030\005 \003(\0132;.WISE.Comms.ValidationPro" +
      "to.ValidationReport.ValidationNode\022-\n\007de" +
      "tails\030\006 \001(\0132\034.google.protobuf.StringValu" +
      "e\032H\n\013ErrorObject\022\014\n\004name\030\001 \001(\t\022+\n\005value\030" +
      "\002 \001(\0132\034.google.protobuf.StringValue\"@\n\nE" +
      "rrorLevel\022\010\n\004NONE\020\000\022\017\n\013INFORMATION\020\001\022\013\n\007" +
      "WARNING\020\002\022\n\n\006SEVERE\020\003B\036\n\032ca.wise.comms.s" +
      "erver.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_WISE_Comms_ValidationProto_ValidationReport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WISE_Comms_ValidationProto_ValidationReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ValidationProto_ValidationReport_descriptor,
        new java.lang.String[] { "Success", "Valid", "LoadWarnings", "ValidationTree", });
    internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_descriptor =
      internal_static_WISE_Comms_ValidationProto_ValidationReport_descriptor.getNestedTypes().get(0);
    internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_descriptor,
        new java.lang.String[] { "ErrorLevel", "ProtobufName", "ErrorValues", "ErrorId", "Children", "Details", });
    internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_ErrorObject_descriptor =
      internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_descriptor.getNestedTypes().get(0);
    internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_ErrorObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WISE_Comms_ValidationProto_ValidationReport_ValidationNode_ErrorObject_descriptor,
        new java.lang.String[] { "Name", "Value", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
